// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/events/v1/base.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BaseEvent 基础事件
type BaseEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 事件ID (UUID)
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// 事件类型 (e.g., "conversation.message.sent")
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// 事件版本 (e.g., "v1")
	EventVersion string `protobuf:"bytes,3,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`
	// 聚合根ID
	AggregateId string `protobuf:"bytes,4,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	// 租户ID
	TenantId string `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// 用户ID
	UserId string `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 事件时间戳
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 事件负载 (具体事件数据)
	Payload *anypb.Any `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	// 元数据
	Metadata map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 关联ID (用于追踪)
	CorrelationId string `protobuf:"bytes,10,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// 因果ID (事件因果关系)
	CausationId   string `protobuf:"bytes,11,opt,name=causation_id,json=causationId,proto3" json:"causation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseEvent) Reset() {
	*x = BaseEvent{}
	mi := &file_api_proto_events_v1_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseEvent) ProtoMessage() {}

func (x *BaseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseEvent.ProtoReflect.Descriptor instead.
func (*BaseEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_base_proto_rawDescGZIP(), []int{0}
}

func (x *BaseEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *BaseEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *BaseEvent) GetEventVersion() string {
	if x != nil {
		return x.EventVersion
	}
	return ""
}

func (x *BaseEvent) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *BaseEvent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BaseEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BaseEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BaseEvent) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BaseEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *BaseEvent) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *BaseEvent) GetCausationId() string {
	if x != nil {
		return x.CausationId
	}
	return ""
}

// EventMetadata 事件元数据
type EventMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 来源服务
	SourceService string `protobuf:"bytes,1,opt,name=source_service,json=sourceService,proto3" json:"source_service,omitempty"`
	// 来源IP
	SourceIp string `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	// 用户代理
	UserAgent string `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// 请求ID
	RequestId string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// 环境 (dev/staging/prod)
	Environment   string `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMetadata) Reset() {
	*x = EventMetadata{}
	mi := &file_api_proto_events_v1_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMetadata) ProtoMessage() {}

func (x *EventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMetadata.ProtoReflect.Descriptor instead.
func (*EventMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_base_proto_rawDescGZIP(), []int{1}
}

func (x *EventMetadata) GetSourceService() string {
	if x != nil {
		return x.SourceService
	}
	return ""
}

func (x *EventMetadata) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *EventMetadata) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *EventMetadata) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EventMetadata) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

var File_api_proto_events_v1_base_proto protoreflect.FileDescriptor

const file_api_proto_events_v1_base_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/events/v1/base.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xf4\x03\n" +
	"\tBaseEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12#\n" +
	"\revent_version\x18\x03 \x01(\tR\feventVersion\x12!\n" +
	"\faggregate_id\x18\x04 \x01(\tR\vaggregateId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12.\n" +
	"\apayload\x18\b \x01(\v2\x14.google.protobuf.AnyR\apayload\x12>\n" +
	"\bmetadata\x18\t \x03(\v2\".events.v1.BaseEvent.MetadataEntryR\bmetadata\x12%\n" +
	"\x0ecorrelation_id\x18\n" +
	" \x01(\tR\rcorrelationId\x12!\n" +
	"\fcausation_id\x18\v \x01(\tR\vcausationId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\rEventMetadata\x12%\n" +
	"\x0esource_service\x18\x01 \x01(\tR\rsourceService\x12\x1b\n" +
	"\tsource_ip\x18\x02 \x01(\tR\bsourceIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironmentB*Z(voicehelper/api/proto/events/v1;eventsv1b\x06proto3"

var (
	file_api_proto_events_v1_base_proto_rawDescOnce sync.Once
	file_api_proto_events_v1_base_proto_rawDescData []byte
)

func file_api_proto_events_v1_base_proto_rawDescGZIP() []byte {
	file_api_proto_events_v1_base_proto_rawDescOnce.Do(func() {
		file_api_proto_events_v1_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_events_v1_base_proto_rawDesc), len(file_api_proto_events_v1_base_proto_rawDesc)))
	})
	return file_api_proto_events_v1_base_proto_rawDescData
}

var file_api_proto_events_v1_base_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_events_v1_base_proto_goTypes = []any{
	(*BaseEvent)(nil),             // 0: events.v1.BaseEvent
	(*EventMetadata)(nil),         // 1: events.v1.EventMetadata
	nil,                           // 2: events.v1.BaseEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 4: google.protobuf.Any
}
var file_api_proto_events_v1_base_proto_depIdxs = []int32{
	3, // 0: events.v1.BaseEvent.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: events.v1.BaseEvent.payload:type_name -> google.protobuf.Any
	2, // 2: events.v1.BaseEvent.metadata:type_name -> events.v1.BaseEvent.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_events_v1_base_proto_init() }
func file_api_proto_events_v1_base_proto_init() {
	if File_api_proto_events_v1_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_events_v1_base_proto_rawDesc), len(file_api_proto_events_v1_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_events_v1_base_proto_goTypes,
		DependencyIndexes: file_api_proto_events_v1_base_proto_depIdxs,
		MessageInfos:      file_api_proto_events_v1_base_proto_msgTypes,
	}.Build()
	File_api_proto_events_v1_base_proto = out.File
	file_api_proto_events_v1_base_proto_goTypes = nil
	file_api_proto_events_v1_base_proto_depIdxs = nil
}
