// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/events/v1/document.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DocumentUploadedPayload 文档上传事件
type DocumentUploadedPayload struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	DocumentId  string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId    string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId      string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Filename    string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // application/pdf, text/plain, etc.
	FileSize    int64                  `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	StoragePath string                 `protobuf:"bytes,7,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"` // MinIO path
	Md5Hash     string                 `protobuf:"bytes,8,opt,name=md5_hash,json=md5Hash,proto3" json:"md5_hash,omitempty"`
	UploadedAt  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	// 元数据
	Metadata      *DocumentMetadata `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentUploadedPayload) Reset() {
	*x = DocumentUploadedPayload{}
	mi := &file_api_proto_events_v1_document_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentUploadedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentUploadedPayload) ProtoMessage() {}

func (x *DocumentUploadedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_document_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentUploadedPayload.ProtoReflect.Descriptor instead.
func (*DocumentUploadedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_document_proto_rawDescGZIP(), []int{0}
}

func (x *DocumentUploadedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentUploadedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DocumentUploadedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DocumentUploadedPayload) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *DocumentUploadedPayload) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *DocumentUploadedPayload) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *DocumentUploadedPayload) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *DocumentUploadedPayload) GetMd5Hash() string {
	if x != nil {
		return x.Md5Hash
	}
	return ""
}

func (x *DocumentUploadedPayload) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *DocumentUploadedPayload) GetMetadata() *DocumentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// DocumentDeletedPayload 文档删除事件
type DocumentDeletedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentDeletedPayload) Reset() {
	*x = DocumentDeletedPayload{}
	mi := &file_api_proto_events_v1_document_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentDeletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentDeletedPayload) ProtoMessage() {}

func (x *DocumentDeletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_document_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentDeletedPayload.ProtoReflect.Descriptor instead.
func (*DocumentDeletedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_document_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentDeletedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentDeletedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DocumentDeletedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DocumentDeletedPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *DocumentDeletedPayload) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// DocumentUpdatedPayload 文档更新事件
type DocumentUpdatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChangeType    string                 `protobuf:"bytes,4,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"` // metadata, content, status
	Changes       map[string]string      `protobuf:"bytes,5,rep,name=changes,proto3" json:"changes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentUpdatedPayload) Reset() {
	*x = DocumentUpdatedPayload{}
	mi := &file_api_proto_events_v1_document_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentUpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentUpdatedPayload) ProtoMessage() {}

func (x *DocumentUpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_document_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentUpdatedPayload.ProtoReflect.Descriptor instead.
func (*DocumentUpdatedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_document_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentUpdatedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentUpdatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DocumentUpdatedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DocumentUpdatedPayload) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *DocumentUpdatedPayload) GetChanges() map[string]string {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *DocumentUpdatedPayload) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DocumentIndexedPayload 文档索引完成事件
type DocumentIndexedPayload struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DocumentId         string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ChunkCount         int32                  `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	VectorCount        int32                  `protobuf:"varint,4,opt,name=vector_count,json=vectorCount,proto3" json:"vector_count,omitempty"`
	EntityCount        int32                  `protobuf:"varint,5,opt,name=entity_count,json=entityCount,proto3" json:"entity_count,omitempty"`
	RelationCount      int32                  `protobuf:"varint,6,opt,name=relation_count,json=relationCount,proto3" json:"relation_count,omitempty"`
	IndexingDurationMs int64                  `protobuf:"varint,7,opt,name=indexing_duration_ms,json=indexingDurationMs,proto3" json:"indexing_duration_ms,omitempty"`
	IndexedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
	// 索引统计
	Stats         *IndexingStats `protobuf:"bytes,9,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentIndexedPayload) Reset() {
	*x = DocumentIndexedPayload{}
	mi := &file_api_proto_events_v1_document_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentIndexedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentIndexedPayload) ProtoMessage() {}

func (x *DocumentIndexedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_document_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentIndexedPayload.ProtoReflect.Descriptor instead.
func (*DocumentIndexedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_document_proto_rawDescGZIP(), []int{3}
}

func (x *DocumentIndexedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentIndexedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DocumentIndexedPayload) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *DocumentIndexedPayload) GetVectorCount() int32 {
	if x != nil {
		return x.VectorCount
	}
	return 0
}

func (x *DocumentIndexedPayload) GetEntityCount() int32 {
	if x != nil {
		return x.EntityCount
	}
	return 0
}

func (x *DocumentIndexedPayload) GetRelationCount() int32 {
	if x != nil {
		return x.RelationCount
	}
	return 0
}

func (x *DocumentIndexedPayload) GetIndexingDurationMs() int64 {
	if x != nil {
		return x.IndexingDurationMs
	}
	return 0
}

func (x *DocumentIndexedPayload) GetIndexedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IndexedAt
	}
	return nil
}

func (x *DocumentIndexedPayload) GetStats() *IndexingStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// DocumentIndexingFailedPayload 文档索引失败事件
type DocumentIndexingFailedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Stage         string                 `protobuf:"bytes,5,opt,name=stage,proto3" json:"stage,omitempty"` // parsing, chunking, embedding, storing
	RetryCount    int32                  `protobuf:"varint,6,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	FailedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=failed_at,json=failedAt,proto3" json:"failed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentIndexingFailedPayload) Reset() {
	*x = DocumentIndexingFailedPayload{}
	mi := &file_api_proto_events_v1_document_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentIndexingFailedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentIndexingFailedPayload) ProtoMessage() {}

func (x *DocumentIndexingFailedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_document_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentIndexingFailedPayload.ProtoReflect.Descriptor instead.
func (*DocumentIndexingFailedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_document_proto_rawDescGZIP(), []int{4}
}

func (x *DocumentIndexingFailedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentIndexingFailedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DocumentIndexingFailedPayload) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *DocumentIndexingFailedPayload) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DocumentIndexingFailedPayload) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *DocumentIndexingFailedPayload) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *DocumentIndexingFailedPayload) GetFailedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FailedAt
	}
	return nil
}

// DocumentScannedPayload 文档病毒扫描事件
type DocumentScannedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IsClean       bool                   `protobuf:"varint,3,opt,name=is_clean,json=isClean,proto3" json:"is_clean,omitempty"`
	ScanResult    string                 `protobuf:"bytes,4,opt,name=scan_result,json=scanResult,proto3" json:"scan_result,omitempty"`
	Threats       []string               `protobuf:"bytes,5,rep,name=threats,proto3" json:"threats,omitempty"`
	ScannedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=scanned_at,json=scannedAt,proto3" json:"scanned_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentScannedPayload) Reset() {
	*x = DocumentScannedPayload{}
	mi := &file_api_proto_events_v1_document_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentScannedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentScannedPayload) ProtoMessage() {}

func (x *DocumentScannedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_document_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentScannedPayload.ProtoReflect.Descriptor instead.
func (*DocumentScannedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_document_proto_rawDescGZIP(), []int{5}
}

func (x *DocumentScannedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentScannedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DocumentScannedPayload) GetIsClean() bool {
	if x != nil {
		return x.IsClean
	}
	return false
}

func (x *DocumentScannedPayload) GetScanResult() string {
	if x != nil {
		return x.ScanResult
	}
	return ""
}

func (x *DocumentScannedPayload) GetThreats() []string {
	if x != nil {
		return x.Threats
	}
	return nil
}

func (x *DocumentScannedPayload) GetScannedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScannedAt
	}
	return nil
}

// DocumentMetadata 文档元数据
type DocumentMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 文档信息
	Title     string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author    string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Language  string `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	PageCount int32  `protobuf:"varint,4,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	WordCount int32  `protobuf:"varint,5,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	// 分类标签
	Tags       []string `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Categories []string `protobuf:"bytes,7,rep,name=categories,proto3" json:"categories,omitempty"`
	// 自定义字段
	CustomFields  map[string]string `protobuf:"bytes,8,rep,name=custom_fields,json=customFields,proto3" json:"custom_fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentMetadata) Reset() {
	*x = DocumentMetadata{}
	mi := &file_api_proto_events_v1_document_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentMetadata) ProtoMessage() {}

func (x *DocumentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_document_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentMetadata.ProtoReflect.Descriptor instead.
func (*DocumentMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_document_proto_rawDescGZIP(), []int{6}
}

func (x *DocumentMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentMetadata) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *DocumentMetadata) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DocumentMetadata) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *DocumentMetadata) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *DocumentMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DocumentMetadata) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *DocumentMetadata) GetCustomFields() map[string]string {
	if x != nil {
		return x.CustomFields
	}
	return nil
}

// IndexingStats 索引统计
type IndexingStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 分块统计
	TotalChunks int32 `protobuf:"varint,1,opt,name=total_chunks,json=totalChunks,proto3" json:"total_chunks,omitempty"`
	TextChunks  int32 `protobuf:"varint,2,opt,name=text_chunks,json=textChunks,proto3" json:"text_chunks,omitempty"`
	TableChunks int32 `protobuf:"varint,3,opt,name=table_chunks,json=tableChunks,proto3" json:"table_chunks,omitempty"`
	ImageChunks int32 `protobuf:"varint,4,opt,name=image_chunks,json=imageChunks,proto3" json:"image_chunks,omitempty"`
	// 向量统计
	VectorDim      int32  `protobuf:"varint,5,opt,name=vector_dim,json=vectorDim,proto3" json:"vector_dim,omitempty"`
	EmbeddingModel string `protobuf:"bytes,6,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	// 图谱统计
	EntitiesExtracted  int32    `protobuf:"varint,7,opt,name=entities_extracted,json=entitiesExtracted,proto3" json:"entities_extracted,omitempty"`
	RelationsExtracted int32    `protobuf:"varint,8,opt,name=relations_extracted,json=relationsExtracted,proto3" json:"relations_extracted,omitempty"`
	EntityTypes        []string `protobuf:"bytes,9,rep,name=entity_types,json=entityTypes,proto3" json:"entity_types,omitempty"`
	RelationTypes      []string `protobuf:"bytes,10,rep,name=relation_types,json=relationTypes,proto3" json:"relation_types,omitempty"`
	// 性能指标
	ParseDurationMs int64 `protobuf:"varint,11,opt,name=parse_duration_ms,json=parseDurationMs,proto3" json:"parse_duration_ms,omitempty"`
	ChunkDurationMs int64 `protobuf:"varint,12,opt,name=chunk_duration_ms,json=chunkDurationMs,proto3" json:"chunk_duration_ms,omitempty"`
	EmbedDurationMs int64 `protobuf:"varint,13,opt,name=embed_duration_ms,json=embedDurationMs,proto3" json:"embed_duration_ms,omitempty"`
	StoreDurationMs int64 `protobuf:"varint,14,opt,name=store_duration_ms,json=storeDurationMs,proto3" json:"store_duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IndexingStats) Reset() {
	*x = IndexingStats{}
	mi := &file_api_proto_events_v1_document_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexingStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexingStats) ProtoMessage() {}

func (x *IndexingStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_document_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexingStats.ProtoReflect.Descriptor instead.
func (*IndexingStats) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_document_proto_rawDescGZIP(), []int{7}
}

func (x *IndexingStats) GetTotalChunks() int32 {
	if x != nil {
		return x.TotalChunks
	}
	return 0
}

func (x *IndexingStats) GetTextChunks() int32 {
	if x != nil {
		return x.TextChunks
	}
	return 0
}

func (x *IndexingStats) GetTableChunks() int32 {
	if x != nil {
		return x.TableChunks
	}
	return 0
}

func (x *IndexingStats) GetImageChunks() int32 {
	if x != nil {
		return x.ImageChunks
	}
	return 0
}

func (x *IndexingStats) GetVectorDim() int32 {
	if x != nil {
		return x.VectorDim
	}
	return 0
}

func (x *IndexingStats) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *IndexingStats) GetEntitiesExtracted() int32 {
	if x != nil {
		return x.EntitiesExtracted
	}
	return 0
}

func (x *IndexingStats) GetRelationsExtracted() int32 {
	if x != nil {
		return x.RelationsExtracted
	}
	return 0
}

func (x *IndexingStats) GetEntityTypes() []string {
	if x != nil {
		return x.EntityTypes
	}
	return nil
}

func (x *IndexingStats) GetRelationTypes() []string {
	if x != nil {
		return x.RelationTypes
	}
	return nil
}

func (x *IndexingStats) GetParseDurationMs() int64 {
	if x != nil {
		return x.ParseDurationMs
	}
	return 0
}

func (x *IndexingStats) GetChunkDurationMs() int64 {
	if x != nil {
		return x.ChunkDurationMs
	}
	return 0
}

func (x *IndexingStats) GetEmbedDurationMs() int64 {
	if x != nil {
		return x.EmbedDurationMs
	}
	return 0
}

func (x *IndexingStats) GetStoreDurationMs() int64 {
	if x != nil {
		return x.StoreDurationMs
	}
	return 0
}

// ChunkCreatedPayload 分块创建事件
type ChunkCreatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkId       string                 `protobuf:"bytes,1,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,5,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	StartOffset   int32                  `protobuf:"varint,6,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset     int32                  `protobuf:"varint,7,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	ChunkType     string                 `protobuf:"bytes,8,opt,name=chunk_type,json=chunkType,proto3" json:"chunk_type,omitempty"` // text, table, code, image
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkCreatedPayload) Reset() {
	*x = ChunkCreatedPayload{}
	mi := &file_api_proto_events_v1_document_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkCreatedPayload) ProtoMessage() {}

func (x *ChunkCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_document_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkCreatedPayload.ProtoReflect.Descriptor instead.
func (*ChunkCreatedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_document_proto_rawDescGZIP(), []int{8}
}

func (x *ChunkCreatedPayload) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *ChunkCreatedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ChunkCreatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ChunkCreatedPayload) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChunkCreatedPayload) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ChunkCreatedPayload) GetStartOffset() int32 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *ChunkCreatedPayload) GetEndOffset() int32 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

func (x *ChunkCreatedPayload) GetChunkType() string {
	if x != nil {
		return x.ChunkType
	}
	return ""
}

func (x *ChunkCreatedPayload) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// VectorStoredPayload 向量存储事件
type VectorStoredPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VectorId       string                 `protobuf:"bytes,1,opt,name=vector_id,json=vectorId,proto3" json:"vector_id,omitempty"`
	ChunkId        string                 `protobuf:"bytes,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	DocumentId     string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectionName string                 `protobuf:"bytes,5,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	VectorDim      int32                  `protobuf:"varint,6,opt,name=vector_dim,json=vectorDim,proto3" json:"vector_dim,omitempty"`
	StoredAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=stored_at,json=storedAt,proto3" json:"stored_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VectorStoredPayload) Reset() {
	*x = VectorStoredPayload{}
	mi := &file_api_proto_events_v1_document_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorStoredPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorStoredPayload) ProtoMessage() {}

func (x *VectorStoredPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_document_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorStoredPayload.ProtoReflect.Descriptor instead.
func (*VectorStoredPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_document_proto_rawDescGZIP(), []int{9}
}

func (x *VectorStoredPayload) GetVectorId() string {
	if x != nil {
		return x.VectorId
	}
	return ""
}

func (x *VectorStoredPayload) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *VectorStoredPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *VectorStoredPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *VectorStoredPayload) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *VectorStoredPayload) GetVectorDim() int32 {
	if x != nil {
		return x.VectorDim
	}
	return 0
}

func (x *VectorStoredPayload) GetStoredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StoredAt
	}
	return nil
}

// GraphNodeCreatedPayload 图节点创建事件
type GraphNodeCreatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	NodeType      string                 `protobuf:"bytes,4,opt,name=node_type,json=nodeType,proto3" json:"node_type,omitempty"` // entity, concept
	NodeLabel     string                 `protobuf:"bytes,5,opt,name=node_label,json=nodeLabel,proto3" json:"node_label,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,6,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphNodeCreatedPayload) Reset() {
	*x = GraphNodeCreatedPayload{}
	mi := &file_api_proto_events_v1_document_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphNodeCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphNodeCreatedPayload) ProtoMessage() {}

func (x *GraphNodeCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_document_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphNodeCreatedPayload.ProtoReflect.Descriptor instead.
func (*GraphNodeCreatedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_document_proto_rawDescGZIP(), []int{10}
}

func (x *GraphNodeCreatedPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GraphNodeCreatedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GraphNodeCreatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GraphNodeCreatedPayload) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *GraphNodeCreatedPayload) GetNodeLabel() string {
	if x != nil {
		return x.NodeLabel
	}
	return ""
}

func (x *GraphNodeCreatedPayload) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GraphNodeCreatedPayload) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GraphRelationCreatedPayload 图关系创建事件
type GraphRelationCreatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelationId    string                 `protobuf:"bytes,1,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SourceNodeId  string                 `protobuf:"bytes,4,opt,name=source_node_id,json=sourceNodeId,proto3" json:"source_node_id,omitempty"`
	TargetNodeId  string                 `protobuf:"bytes,5,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	RelationType  string                 `protobuf:"bytes,6,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Confidence    float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Properties    map[string]string      `protobuf:"bytes,8,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphRelationCreatedPayload) Reset() {
	*x = GraphRelationCreatedPayload{}
	mi := &file_api_proto_events_v1_document_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphRelationCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphRelationCreatedPayload) ProtoMessage() {}

func (x *GraphRelationCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_document_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphRelationCreatedPayload.ProtoReflect.Descriptor instead.
func (*GraphRelationCreatedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_document_proto_rawDescGZIP(), []int{11}
}

func (x *GraphRelationCreatedPayload) GetRelationId() string {
	if x != nil {
		return x.RelationId
	}
	return ""
}

func (x *GraphRelationCreatedPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GraphRelationCreatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GraphRelationCreatedPayload) GetSourceNodeId() string {
	if x != nil {
		return x.SourceNodeId
	}
	return ""
}

func (x *GraphRelationCreatedPayload) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *GraphRelationCreatedPayload) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *GraphRelationCreatedPayload) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *GraphRelationCreatedPayload) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *GraphRelationCreatedPayload) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_proto_events_v1_document_proto protoreflect.FileDescriptor

const file_api_proto_events_v1_document_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/events/v1/document.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x03\n" +
	"\x17DocumentUploadedPayload\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\x03R\bfileSize\x12!\n" +
	"\fstorage_path\x18\a \x01(\tR\vstoragePath\x12\x19\n" +
	"\bmd5_hash\x18\b \x01(\tR\amd5Hash\x12;\n" +
	"\vuploaded_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\x127\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1b.events.v1.DocumentMetadataR\bmetadata\"\xc2\x01\n" +
	"\x16DocumentDeletedPayload\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xd1\x02\n" +
	"\x16DocumentUpdatedPayload\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1f\n" +
	"\vchange_type\x18\x04 \x01(\tR\n" +
	"changeType\x12H\n" +
	"\achanges\x18\x05 \x03(\v2..events.v1.DocumentUpdatedPayload.ChangesEntryR\achanges\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a:\n" +
	"\fChangesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x81\x03\n" +
	"\x16DocumentIndexedPayload\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\x12!\n" +
	"\fvector_count\x18\x04 \x01(\x05R\vvectorCount\x12!\n" +
	"\fentity_count\x18\x05 \x01(\x05R\ventityCount\x12%\n" +
	"\x0erelation_count\x18\x06 \x01(\x05R\rrelationCount\x120\n" +
	"\x14indexing_duration_ms\x18\a \x01(\x03R\x12indexingDurationMs\x129\n" +
	"\n" +
	"indexed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tindexedAt\x12.\n" +
	"\x05stats\x18\t \x01(\v2\x18.events.v1.IndexingStatsR\x05stats\"\x91\x02\n" +
	"\x1dDocumentIndexingFailedPayload\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x14\n" +
	"\x05stage\x18\x05 \x01(\tR\x05stage\x12\x1f\n" +
	"\vretry_count\x18\x06 \x01(\x05R\n" +
	"retryCount\x127\n" +
	"\tfailed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bfailedAt\"\xe7\x01\n" +
	"\x16DocumentScannedPayload\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x19\n" +
	"\bis_clean\x18\x03 \x01(\bR\aisClean\x12\x1f\n" +
	"\vscan_result\x18\x04 \x01(\tR\n" +
	"scanResult\x12\x18\n" +
	"\athreats\x18\x05 \x03(\tR\athreats\x129\n" +
	"\n" +
	"scanned_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tscannedAt\"\xe3\x02\n" +
	"\x10DocumentMetadata\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1d\n" +
	"\n" +
	"page_count\x18\x04 \x01(\x05R\tpageCount\x12\x1d\n" +
	"\n" +
	"word_count\x18\x05 \x01(\x05R\twordCount\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"categories\x18\a \x03(\tR\n" +
	"categories\x12R\n" +
	"\rcustom_fields\x18\b \x03(\v2-.events.v1.DocumentMetadata.CustomFieldsEntryR\fcustomFields\x1a?\n" +
	"\x11CustomFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x04\n" +
	"\rIndexingStats\x12!\n" +
	"\ftotal_chunks\x18\x01 \x01(\x05R\vtotalChunks\x12\x1f\n" +
	"\vtext_chunks\x18\x02 \x01(\x05R\n" +
	"textChunks\x12!\n" +
	"\ftable_chunks\x18\x03 \x01(\x05R\vtableChunks\x12!\n" +
	"\fimage_chunks\x18\x04 \x01(\x05R\vimageChunks\x12\x1d\n" +
	"\n" +
	"vector_dim\x18\x05 \x01(\x05R\tvectorDim\x12'\n" +
	"\x0fembedding_model\x18\x06 \x01(\tR\x0eembeddingModel\x12-\n" +
	"\x12entities_extracted\x18\a \x01(\x05R\x11entitiesExtracted\x12/\n" +
	"\x13relations_extracted\x18\b \x01(\x05R\x12relationsExtracted\x12!\n" +
	"\fentity_types\x18\t \x03(\tR\ventityTypes\x12%\n" +
	"\x0erelation_types\x18\n" +
	" \x03(\tR\rrelationTypes\x12*\n" +
	"\x11parse_duration_ms\x18\v \x01(\x03R\x0fparseDurationMs\x12*\n" +
	"\x11chunk_duration_ms\x18\f \x01(\x03R\x0fchunkDurationMs\x12*\n" +
	"\x11embed_duration_ms\x18\r \x01(\x03R\x0fembedDurationMs\x12*\n" +
	"\x11store_duration_ms\x18\x0e \x01(\x03R\x0fstoreDurationMs\"\xc5\x02\n" +
	"\x13ChunkCreatedPayload\x12\x19\n" +
	"\bchunk_id\x18\x01 \x01(\tR\achunkId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1f\n" +
	"\vchunk_index\x18\x05 \x01(\x05R\n" +
	"chunkIndex\x12!\n" +
	"\fstart_offset\x18\x06 \x01(\x05R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\a \x01(\x05R\tendOffset\x12\x1d\n" +
	"\n" +
	"chunk_type\x18\b \x01(\tR\tchunkType\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x8c\x02\n" +
	"\x13VectorStoredPayload\x12\x1b\n" +
	"\tvector_id\x18\x01 \x01(\tR\bvectorId\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\tR\achunkId\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12'\n" +
	"\x0fcollection_name\x18\x05 \x01(\tR\x0ecollectionName\x12\x1d\n" +
	"\n" +
	"vector_dim\x18\x06 \x01(\x05R\tvectorDim\x127\n" +
	"\tstored_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bstoredAt\"\xfa\x02\n" +
	"\x17GraphNodeCreatedPayload\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1b\n" +
	"\tnode_type\x18\x04 \x01(\tR\bnodeType\x12\x1d\n" +
	"\n" +
	"node_label\x18\x05 \x01(\tR\tnodeLabel\x12R\n" +
	"\n" +
	"properties\x18\x06 \x03(\v22.events.v1.GraphNodeCreatedPayload.PropertiesEntryR\n" +
	"properties\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdf\x03\n" +
	"\x1bGraphRelationCreatedPayload\x12\x1f\n" +
	"\vrelation_id\x18\x01 \x01(\tR\n" +
	"relationId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12$\n" +
	"\x0esource_node_id\x18\x04 \x01(\tR\fsourceNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x05 \x01(\tR\ftargetNodeId\x12#\n" +
	"\rrelation_type\x18\x06 \x01(\tR\frelationType\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12V\n" +
	"\n" +
	"properties\x18\b \x03(\v26.events.v1.GraphRelationCreatedPayload.PropertiesEntryR\n" +
	"properties\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B*Z(voicehelper/api/proto/events/v1;eventsv1b\x06proto3"

var (
	file_api_proto_events_v1_document_proto_rawDescOnce sync.Once
	file_api_proto_events_v1_document_proto_rawDescData []byte
)

func file_api_proto_events_v1_document_proto_rawDescGZIP() []byte {
	file_api_proto_events_v1_document_proto_rawDescOnce.Do(func() {
		file_api_proto_events_v1_document_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_events_v1_document_proto_rawDesc), len(file_api_proto_events_v1_document_proto_rawDesc)))
	})
	return file_api_proto_events_v1_document_proto_rawDescData
}

var file_api_proto_events_v1_document_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_events_v1_document_proto_goTypes = []any{
	(*DocumentUploadedPayload)(nil),       // 0: events.v1.DocumentUploadedPayload
	(*DocumentDeletedPayload)(nil),        // 1: events.v1.DocumentDeletedPayload
	(*DocumentUpdatedPayload)(nil),        // 2: events.v1.DocumentUpdatedPayload
	(*DocumentIndexedPayload)(nil),        // 3: events.v1.DocumentIndexedPayload
	(*DocumentIndexingFailedPayload)(nil), // 4: events.v1.DocumentIndexingFailedPayload
	(*DocumentScannedPayload)(nil),        // 5: events.v1.DocumentScannedPayload
	(*DocumentMetadata)(nil),              // 6: events.v1.DocumentMetadata
	(*IndexingStats)(nil),                 // 7: events.v1.IndexingStats
	(*ChunkCreatedPayload)(nil),           // 8: events.v1.ChunkCreatedPayload
	(*VectorStoredPayload)(nil),           // 9: events.v1.VectorStoredPayload
	(*GraphNodeCreatedPayload)(nil),       // 10: events.v1.GraphNodeCreatedPayload
	(*GraphRelationCreatedPayload)(nil),   // 11: events.v1.GraphRelationCreatedPayload
	nil,                                   // 12: events.v1.DocumentUpdatedPayload.ChangesEntry
	nil,                                   // 13: events.v1.DocumentMetadata.CustomFieldsEntry
	nil,                                   // 14: events.v1.GraphNodeCreatedPayload.PropertiesEntry
	nil,                                   // 15: events.v1.GraphRelationCreatedPayload.PropertiesEntry
	(*timestamppb.Timestamp)(nil),         // 16: google.protobuf.Timestamp
}
var file_api_proto_events_v1_document_proto_depIdxs = []int32{
	16, // 0: events.v1.DocumentUploadedPayload.uploaded_at:type_name -> google.protobuf.Timestamp
	6,  // 1: events.v1.DocumentUploadedPayload.metadata:type_name -> events.v1.DocumentMetadata
	16, // 2: events.v1.DocumentDeletedPayload.deleted_at:type_name -> google.protobuf.Timestamp
	12, // 3: events.v1.DocumentUpdatedPayload.changes:type_name -> events.v1.DocumentUpdatedPayload.ChangesEntry
	16, // 4: events.v1.DocumentUpdatedPayload.updated_at:type_name -> google.protobuf.Timestamp
	16, // 5: events.v1.DocumentIndexedPayload.indexed_at:type_name -> google.protobuf.Timestamp
	7,  // 6: events.v1.DocumentIndexedPayload.stats:type_name -> events.v1.IndexingStats
	16, // 7: events.v1.DocumentIndexingFailedPayload.failed_at:type_name -> google.protobuf.Timestamp
	16, // 8: events.v1.DocumentScannedPayload.scanned_at:type_name -> google.protobuf.Timestamp
	13, // 9: events.v1.DocumentMetadata.custom_fields:type_name -> events.v1.DocumentMetadata.CustomFieldsEntry
	16, // 10: events.v1.ChunkCreatedPayload.created_at:type_name -> google.protobuf.Timestamp
	16, // 11: events.v1.VectorStoredPayload.stored_at:type_name -> google.protobuf.Timestamp
	14, // 12: events.v1.GraphNodeCreatedPayload.properties:type_name -> events.v1.GraphNodeCreatedPayload.PropertiesEntry
	16, // 13: events.v1.GraphNodeCreatedPayload.created_at:type_name -> google.protobuf.Timestamp
	15, // 14: events.v1.GraphRelationCreatedPayload.properties:type_name -> events.v1.GraphRelationCreatedPayload.PropertiesEntry
	16, // 15: events.v1.GraphRelationCreatedPayload.created_at:type_name -> google.protobuf.Timestamp
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_events_v1_document_proto_init() }
func file_api_proto_events_v1_document_proto_init() {
	if File_api_proto_events_v1_document_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_events_v1_document_proto_rawDesc), len(file_api_proto_events_v1_document_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_events_v1_document_proto_goTypes,
		DependencyIndexes: file_api_proto_events_v1_document_proto_depIdxs,
		MessageInfos:      file_api_proto_events_v1_document_proto_msgTypes,
	}.Build()
	File_api_proto_events_v1_document_proto = out.File
	file_api_proto_events_v1_document_proto_goTypes = nil
	file_api_proto_events_v1_document_proto_depIdxs = nil
}
