// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/events/v1/identity.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserRegisteredPayload 用户注册事件
type UserRegisteredPayload struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Email              string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Username           string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	RegistrationSource string                 `protobuf:"bytes,5,opt,name=registration_source,json=registrationSource,proto3" json:"registration_source,omitempty"` // web, api, oauth
	OauthProvider      string                 `protobuf:"bytes,6,opt,name=oauth_provider,json=oauthProvider,proto3" json:"oauth_provider,omitempty"`                // google, github, etc.
	RegisteredAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserRegisteredPayload) Reset() {
	*x = UserRegisteredPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisteredPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisteredPayload) ProtoMessage() {}

func (x *UserRegisteredPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisteredPayload.ProtoReflect.Descriptor instead.
func (*UserRegisteredPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *UserRegisteredPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserRegisteredPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserRegisteredPayload) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserRegisteredPayload) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserRegisteredPayload) GetRegistrationSource() string {
	if x != nil {
		return x.RegistrationSource
	}
	return ""
}

func (x *UserRegisteredPayload) GetOauthProvider() string {
	if x != nil {
		return x.OauthProvider
	}
	return ""
}

func (x *UserRegisteredPayload) GetRegisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegisteredAt
	}
	return nil
}

// UserLoginPayload 用户登录事件
type UserLoginPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	LoginMethod   string                 `protobuf:"bytes,3,opt,name=login_method,json=loginMethod,proto3" json:"login_method,omitempty"` // password, oauth, sso
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	DeviceType    string                 `protobuf:"bytes,6,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"` // web, mobile, desktop
	MfaEnabled    bool                   `protobuf:"varint,7,opt,name=mfa_enabled,json=mfaEnabled,proto3" json:"mfa_enabled,omitempty"`
	Success       bool                   `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	FailureReason string                 `protobuf:"bytes,9,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	LoginAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=login_at,json=loginAt,proto3" json:"login_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginPayload) Reset() {
	*x = UserLoginPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginPayload) ProtoMessage() {}

func (x *UserLoginPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginPayload.ProtoReflect.Descriptor instead.
func (*UserLoginPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *UserLoginPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLoginPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserLoginPayload) GetLoginMethod() string {
	if x != nil {
		return x.LoginMethod
	}
	return ""
}

func (x *UserLoginPayload) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *UserLoginPayload) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *UserLoginPayload) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *UserLoginPayload) GetMfaEnabled() bool {
	if x != nil {
		return x.MfaEnabled
	}
	return false
}

func (x *UserLoginPayload) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserLoginPayload) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *UserLoginPayload) GetLoginAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LoginAt
	}
	return nil
}

// UserLogoutPayload 用户登出事件
type UserLogoutPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId          string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId         string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionDurationMs int64                  `protobuf:"varint,4,opt,name=session_duration_ms,json=sessionDurationMs,proto3" json:"session_duration_ms,omitempty"`
	LogoutAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=logout_at,json=logoutAt,proto3" json:"logout_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserLogoutPayload) Reset() {
	*x = UserLogoutPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogoutPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogoutPayload) ProtoMessage() {}

func (x *UserLogoutPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogoutPayload.ProtoReflect.Descriptor instead.
func (*UserLogoutPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *UserLogoutPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserLogoutPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserLogoutPayload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *UserLogoutPayload) GetSessionDurationMs() int64 {
	if x != nil {
		return x.SessionDurationMs
	}
	return 0
}

func (x *UserLogoutPayload) GetLogoutAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LogoutAt
	}
	return nil
}

// UserUpdatedPayload 用户更新事件
type UserUpdatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	ChangedFields []string               `protobuf:"bytes,4,rep,name=changed_fields,json=changedFields,proto3" json:"changed_fields,omitempty"`
	OldValues     map[string]string      `protobuf:"bytes,5,rep,name=old_values,json=oldValues,proto3" json:"old_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NewValues     map[string]string      `protobuf:"bytes,6,rep,name=new_values,json=newValues,proto3" json:"new_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdatedPayload) Reset() {
	*x = UserUpdatedPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdatedPayload) ProtoMessage() {}

func (x *UserUpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdatedPayload.ProtoReflect.Descriptor instead.
func (*UserUpdatedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *UserUpdatedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserUpdatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserUpdatedPayload) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *UserUpdatedPayload) GetChangedFields() []string {
	if x != nil {
		return x.ChangedFields
	}
	return nil
}

func (x *UserUpdatedPayload) GetOldValues() map[string]string {
	if x != nil {
		return x.OldValues
	}
	return nil
}

func (x *UserUpdatedPayload) GetNewValues() map[string]string {
	if x != nil {
		return x.NewValues
	}
	return nil
}

func (x *UserUpdatedPayload) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// UserDeletedPayload 用户删除事件
type UserDeletedPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	DeletedBy      string                 `protobuf:"bytes,3,opt,name=deleted_by,json=deletedBy,proto3" json:"deleted_by,omitempty"`
	DeletionReason string                 `protobuf:"bytes,4,opt,name=deletion_reason,json=deletionReason,proto3" json:"deletion_reason,omitempty"`
	SoftDelete     bool                   `protobuf:"varint,5,opt,name=soft_delete,json=softDelete,proto3" json:"soft_delete,omitempty"` // true: 软删除, false: 硬删除
	DeletedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserDeletedPayload) Reset() {
	*x = UserDeletedPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeletedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeletedPayload) ProtoMessage() {}

func (x *UserDeletedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeletedPayload.ProtoReflect.Descriptor instead.
func (*UserDeletedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *UserDeletedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserDeletedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UserDeletedPayload) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

func (x *UserDeletedPayload) GetDeletionReason() string {
	if x != nil {
		return x.DeletionReason
	}
	return ""
}

func (x *UserDeletedPayload) GetSoftDelete() bool {
	if x != nil {
		return x.SoftDelete
	}
	return false
}

func (x *UserDeletedPayload) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// PasswordChangedPayload 密码修改事件
type PasswordChangedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ChangeMethod  string                 `protobuf:"bytes,3,opt,name=change_method,json=changeMethod,proto3" json:"change_method,omitempty"` // user_initiated, admin_reset, forgot_password
	InitiatedBy   string                 `protobuf:"bytes,4,opt,name=initiated_by,json=initiatedBy,proto3" json:"initiated_by,omitempty"`
	ChangedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordChangedPayload) Reset() {
	*x = PasswordChangedPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordChangedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordChangedPayload) ProtoMessage() {}

func (x *PasswordChangedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordChangedPayload.ProtoReflect.Descriptor instead.
func (*PasswordChangedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *PasswordChangedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PasswordChangedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PasswordChangedPayload) GetChangeMethod() string {
	if x != nil {
		return x.ChangeMethod
	}
	return ""
}

func (x *PasswordChangedPayload) GetInitiatedBy() string {
	if x != nil {
		return x.InitiatedBy
	}
	return ""
}

func (x *PasswordChangedPayload) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

// TenantCreatedPayload 租户创建事件
type TenantCreatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TenantName    string                 `protobuf:"bytes,2,opt,name=tenant_name,json=tenantName,proto3" json:"tenant_name,omitempty"`
	Plan          string                 `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"` // free, basic, pro, enterprise
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantCreatedPayload) Reset() {
	*x = TenantCreatedPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantCreatedPayload) ProtoMessage() {}

func (x *TenantCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantCreatedPayload.ProtoReflect.Descriptor instead.
func (*TenantCreatedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *TenantCreatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantCreatedPayload) GetTenantName() string {
	if x != nil {
		return x.TenantName
	}
	return ""
}

func (x *TenantCreatedPayload) GetPlan() string {
	if x != nil {
		return x.Plan
	}
	return ""
}

func (x *TenantCreatedPayload) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *TenantCreatedPayload) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// TenantUpdatedPayload 租户更新事件
type TenantUpdatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,2,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	ChangedFields []string               `protobuf:"bytes,3,rep,name=changed_fields,json=changedFields,proto3" json:"changed_fields,omitempty"`
	OldValues     map[string]string      `protobuf:"bytes,4,rep,name=old_values,json=oldValues,proto3" json:"old_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NewValues     map[string]string      `protobuf:"bytes,5,rep,name=new_values,json=newValues,proto3" json:"new_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUpdatedPayload) Reset() {
	*x = TenantUpdatedPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUpdatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUpdatedPayload) ProtoMessage() {}

func (x *TenantUpdatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUpdatedPayload.ProtoReflect.Descriptor instead.
func (*TenantUpdatedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{7}
}

func (x *TenantUpdatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantUpdatedPayload) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *TenantUpdatedPayload) GetChangedFields() []string {
	if x != nil {
		return x.ChangedFields
	}
	return nil
}

func (x *TenantUpdatedPayload) GetOldValues() map[string]string {
	if x != nil {
		return x.OldValues
	}
	return nil
}

func (x *TenantUpdatedPayload) GetNewValues() map[string]string {
	if x != nil {
		return x.NewValues
	}
	return nil
}

func (x *TenantUpdatedPayload) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// TenantSuspendedPayload 租户暂停事件
type TenantSuspendedPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SuspendedBy      string                 `protobuf:"bytes,2,opt,name=suspended_by,json=suspendedBy,proto3" json:"suspended_by,omitempty"`
	SuspensionReason string                 `protobuf:"bytes,3,opt,name=suspension_reason,json=suspensionReason,proto3" json:"suspension_reason,omitempty"` // payment_failed, abuse, admin_action
	SuspendedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=suspended_at,json=suspendedAt,proto3" json:"suspended_at,omitempty"`
	ResumeAt         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=resume_at,json=resumeAt,proto3" json:"resume_at,omitempty"` // 预计恢复时间
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TenantSuspendedPayload) Reset() {
	*x = TenantSuspendedPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantSuspendedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantSuspendedPayload) ProtoMessage() {}

func (x *TenantSuspendedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantSuspendedPayload.ProtoReflect.Descriptor instead.
func (*TenantSuspendedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *TenantSuspendedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TenantSuspendedPayload) GetSuspendedBy() string {
	if x != nil {
		return x.SuspendedBy
	}
	return ""
}

func (x *TenantSuspendedPayload) GetSuspensionReason() string {
	if x != nil {
		return x.SuspensionReason
	}
	return ""
}

func (x *TenantSuspendedPayload) GetSuspendedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SuspendedAt
	}
	return nil
}

func (x *TenantSuspendedPayload) GetResumeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResumeAt
	}
	return nil
}

// RoleAssignedPayload 角色分配事件
type RoleAssignedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName      string                 `protobuf:"bytes,4,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	AssignedBy    string                 `protobuf:"bytes,5,opt,name=assigned_by,json=assignedBy,proto3" json:"assigned_by,omitempty"`
	AssignedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAssignedPayload) Reset() {
	*x = RoleAssignedPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssignedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssignedPayload) ProtoMessage() {}

func (x *RoleAssignedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssignedPayload.ProtoReflect.Descriptor instead.
func (*RoleAssignedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{9}
}

func (x *RoleAssignedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoleAssignedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RoleAssignedPayload) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleAssignedPayload) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleAssignedPayload) GetAssignedBy() string {
	if x != nil {
		return x.AssignedBy
	}
	return ""
}

func (x *RoleAssignedPayload) GetAssignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AssignedAt
	}
	return nil
}

// RoleRevokedPayload 角色撤销事件
type RoleRevokedPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RoleId           string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	RoleName         string                 `protobuf:"bytes,4,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RevokedBy        string                 `protobuf:"bytes,5,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	RevocationReason string                 `protobuf:"bytes,6,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"`
	RevokedAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RoleRevokedPayload) Reset() {
	*x = RoleRevokedPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleRevokedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRevokedPayload) ProtoMessage() {}

func (x *RoleRevokedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRevokedPayload.ProtoReflect.Descriptor instead.
func (*RoleRevokedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{10}
}

func (x *RoleRevokedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoleRevokedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RoleRevokedPayload) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleRevokedPayload) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleRevokedPayload) GetRevokedBy() string {
	if x != nil {
		return x.RevokedBy
	}
	return ""
}

func (x *RoleRevokedPayload) GetRevocationReason() string {
	if x != nil {
		return x.RevocationReason
	}
	return ""
}

func (x *RoleRevokedPayload) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

// PermissionChangedPayload 权限变更事件
type PermissionChangedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Granted       bool                   `protobuf:"varint,5,opt,name=granted,proto3" json:"granted,omitempty"` // true: 授予, false: 撤销
	ChangedBy     string                 `protobuf:"bytes,6,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	ChangedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionChangedPayload) Reset() {
	*x = PermissionChangedPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionChangedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionChangedPayload) ProtoMessage() {}

func (x *PermissionChangedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionChangedPayload.ProtoReflect.Descriptor instead.
func (*PermissionChangedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{11}
}

func (x *PermissionChangedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PermissionChangedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PermissionChangedPayload) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionChangedPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PermissionChangedPayload) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *PermissionChangedPayload) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *PermissionChangedPayload) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

// SessionCreatedPayload 会话创建事件
type SessionCreatedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IpAddress     string                 `protobuf:"bytes,4,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,6,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionCreatedPayload) Reset() {
	*x = SessionCreatedPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionCreatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionCreatedPayload) ProtoMessage() {}

func (x *SessionCreatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionCreatedPayload.ProtoReflect.Descriptor instead.
func (*SessionCreatedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{12}
}

func (x *SessionCreatedPayload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionCreatedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionCreatedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SessionCreatedPayload) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SessionCreatedPayload) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SessionCreatedPayload) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *SessionCreatedPayload) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// SessionExpiredPayload 会话过期事件
type SessionExpiredPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ExpirationReason string                 `protobuf:"bytes,4,opt,name=expiration_reason,json=expirationReason,proto3" json:"expiration_reason,omitempty"` // timeout, manual_logout, security_policy
	ExpiredAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionExpiredPayload) Reset() {
	*x = SessionExpiredPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionExpiredPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionExpiredPayload) ProtoMessage() {}

func (x *SessionExpiredPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionExpiredPayload.ProtoReflect.Descriptor instead.
func (*SessionExpiredPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{13}
}

func (x *SessionExpiredPayload) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionExpiredPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionExpiredPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SessionExpiredPayload) GetExpirationReason() string {
	if x != nil {
		return x.ExpirationReason
	}
	return ""
}

func (x *SessionExpiredPayload) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

// TokenGeneratedPayload Token 生成事件
type TokenGeneratedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"` // access, refresh, api_key
	TtlSeconds    int64                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	Scopes        []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenGeneratedPayload) Reset() {
	*x = TokenGeneratedPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenGeneratedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenGeneratedPayload) ProtoMessage() {}

func (x *TokenGeneratedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenGeneratedPayload.ProtoReflect.Descriptor instead.
func (*TokenGeneratedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{14}
}

func (x *TokenGeneratedPayload) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *TokenGeneratedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenGeneratedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TokenGeneratedPayload) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenGeneratedPayload) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *TokenGeneratedPayload) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *TokenGeneratedPayload) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

// TokenRevokedPayload Token 撤销事件
type TokenRevokedPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TokenId          string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	RevocationReason string                 `protobuf:"bytes,4,opt,name=revocation_reason,json=revocationReason,proto3" json:"revocation_reason,omitempty"` // expired, user_logout, security_breach
	RevokedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenRevokedPayload) Reset() {
	*x = TokenRevokedPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRevokedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRevokedPayload) ProtoMessage() {}

func (x *TokenRevokedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRevokedPayload.ProtoReflect.Descriptor instead.
func (*TokenRevokedPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{15}
}

func (x *TokenRevokedPayload) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *TokenRevokedPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TokenRevokedPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TokenRevokedPayload) GetRevocationReason() string {
	if x != nil {
		return x.RevocationReason
	}
	return ""
}

func (x *TokenRevokedPayload) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

// SecurityEventPayload 安全事件
type SecurityEventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // brute_force, suspicious_login, unauthorized_access
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`                    // low, medium, high, critical
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	AutoBlocked   bool                   `protobuf:"varint,8,opt,name=auto_blocked,json=autoBlocked,proto3" json:"auto_blocked,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityEventPayload) Reset() {
	*x = SecurityEventPayload{}
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityEventPayload) ProtoMessage() {}

func (x *SecurityEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_v1_identity_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityEventPayload.ProtoReflect.Descriptor instead.
func (*SecurityEventPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_events_v1_identity_proto_rawDescGZIP(), []int{16}
}

func (x *SecurityEventPayload) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SecurityEventPayload) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SecurityEventPayload) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SecurityEventPayload) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *SecurityEventPayload) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *SecurityEventPayload) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SecurityEventPayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecurityEventPayload) GetAutoBlocked() bool {
	if x != nil {
		return x.AutoBlocked
	}
	return false
}

func (x *SecurityEventPayload) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

var File_api_proto_events_v1_identity_proto protoreflect.FileDescriptor

const file_api_proto_events_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/events/v1/identity.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x02\n" +
	"\x15UserRegisteredPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12/\n" +
	"\x13registration_source\x18\x05 \x01(\tR\x12registrationSource\x12%\n" +
	"\x0eoauth_provider\x18\x06 \x01(\tR\roauthProvider\x12?\n" +
	"\rregistered_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\fregisteredAt\"\xe3\x02\n" +
	"\x10UserLoginPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12!\n" +
	"\flogin_method\x18\x03 \x01(\tR\vloginMethod\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vdevice_type\x18\x06 \x01(\tR\n" +
	"deviceType\x12\x1f\n" +
	"\vmfa_enabled\x18\a \x01(\bR\n" +
	"mfaEnabled\x12\x18\n" +
	"\asuccess\x18\b \x01(\bR\asuccess\x12%\n" +
	"\x0efailure_reason\x18\t \x01(\tR\rfailureReason\x125\n" +
	"\blogin_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aloginAt\"\xd1\x01\n" +
	"\x11UserLogoutPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12.\n" +
	"\x13session_duration_ms\x18\x04 \x01(\x03R\x11sessionDurationMs\x127\n" +
	"\tlogout_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blogoutAt\"\xe1\x03\n" +
	"\x12UserUpdatedPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedBy\x12%\n" +
	"\x0echanged_fields\x18\x04 \x03(\tR\rchangedFields\x12K\n" +
	"\n" +
	"old_values\x18\x05 \x03(\v2,.events.v1.UserUpdatedPayload.OldValuesEntryR\toldValues\x12K\n" +
	"\n" +
	"new_values\x18\x06 \x03(\v2,.events.v1.UserUpdatedPayload.NewValuesEntryR\tnewValues\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a<\n" +
	"\x0eOldValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eNewValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x01\n" +
	"\x12UserDeletedPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"deleted_by\x18\x03 \x01(\tR\tdeletedBy\x12'\n" +
	"\x0fdeletion_reason\x18\x04 \x01(\tR\x0edeletionReason\x12\x1f\n" +
	"\vsoft_delete\x18\x05 \x01(\bR\n" +
	"softDelete\x129\n" +
	"\n" +
	"deleted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xd1\x01\n" +
	"\x16PasswordChangedPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12#\n" +
	"\rchange_method\x18\x03 \x01(\tR\fchangeMethod\x12!\n" +
	"\finitiated_by\x18\x04 \x01(\tR\vinitiatedBy\x129\n" +
	"\n" +
	"changed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\"\xc2\x01\n" +
	"\x14TenantCreatedPayload\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1f\n" +
	"\vtenant_name\x18\x02 \x01(\tR\n" +
	"tenantName\x12\x12\n" +
	"\x04plan\x18\x03 \x01(\tR\x04plan\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xce\x03\n" +
	"\x14TenantUpdatedPayload\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x02 \x01(\tR\tupdatedBy\x12%\n" +
	"\x0echanged_fields\x18\x03 \x03(\tR\rchangedFields\x12M\n" +
	"\n" +
	"old_values\x18\x04 \x03(\v2..events.v1.TenantUpdatedPayload.OldValuesEntryR\toldValues\x12M\n" +
	"\n" +
	"new_values\x18\x05 \x03(\v2..events.v1.TenantUpdatedPayload.NewValuesEntryR\tnewValues\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a<\n" +
	"\x0eOldValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a<\n" +
	"\x0eNewValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfd\x01\n" +
	"\x16TenantSuspendedPayload\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fsuspended_by\x18\x02 \x01(\tR\vsuspendedBy\x12+\n" +
	"\x11suspension_reason\x18\x03 \x01(\tR\x10suspensionReason\x12=\n" +
	"\fsuspended_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vsuspendedAt\x127\n" +
	"\tresume_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bresumeAt\"\xdf\x01\n" +
	"\x13RoleAssignedPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x04 \x01(\tR\broleName\x12\x1f\n" +
	"\vassigned_by\x18\x05 \x01(\tR\n" +
	"assignedBy\x12;\n" +
	"\vassigned_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"assignedAt\"\x87\x02\n" +
	"\x12RoleRevokedPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12\x1b\n" +
	"\trole_name\x18\x04 \x01(\tR\broleName\x12\x1d\n" +
	"\n" +
	"revoked_by\x18\x05 \x01(\tR\trevokedBy\x12+\n" +
	"\x11revocation_reason\x18\x06 \x01(\tR\x10revocationReason\x129\n" +
	"\n" +
	"revoked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\xf8\x01\n" +
	"\x18PermissionChangedPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x18\n" +
	"\agranted\x18\x05 \x01(\bR\agranted\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x06 \x01(\tR\tchangedBy\x129\n" +
	"\n" +
	"changed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\"\x86\x02\n" +
	"\x15SessionCreatedPayload\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x04 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vttl_seconds\x18\x06 \x01(\x03R\n" +
	"ttlSeconds\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xd4\x01\n" +
	"\x15SessionExpiredPayload\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12+\n" +
	"\x11expiration_reason\x18\x04 \x01(\tR\x10expirationReason\x129\n" +
	"\n" +
	"expired_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\"\xff\x01\n" +
	"\x15TokenGeneratedPayload\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x03R\n" +
	"ttlSeconds\x12\x16\n" +
	"\x06scopes\x18\x06 \x03(\tR\x06scopes\x12=\n" +
	"\fgenerated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"\xce\x01\n" +
	"\x13TokenRevokedPayload\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12+\n" +
	"\x11revocation_reason\x18\x04 \x01(\tR\x10revocationReason\x129\n" +
	"\n" +
	"revoked_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt\"\xc7\x02\n" +
	"\x14SecurityEventPayload\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12!\n" +
	"\fauto_blocked\x18\b \x01(\bR\vautoBlocked\x12;\n" +
	"\voccurred_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAtB*Z(voicehelper/api/proto/events/v1;eventsv1b\x06proto3"

var (
	file_api_proto_events_v1_identity_proto_rawDescOnce sync.Once
	file_api_proto_events_v1_identity_proto_rawDescData []byte
)

func file_api_proto_events_v1_identity_proto_rawDescGZIP() []byte {
	file_api_proto_events_v1_identity_proto_rawDescOnce.Do(func() {
		file_api_proto_events_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_events_v1_identity_proto_rawDesc), len(file_api_proto_events_v1_identity_proto_rawDesc)))
	})
	return file_api_proto_events_v1_identity_proto_rawDescData
}

var file_api_proto_events_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_events_v1_identity_proto_goTypes = []any{
	(*UserRegisteredPayload)(nil),    // 0: events.v1.UserRegisteredPayload
	(*UserLoginPayload)(nil),         // 1: events.v1.UserLoginPayload
	(*UserLogoutPayload)(nil),        // 2: events.v1.UserLogoutPayload
	(*UserUpdatedPayload)(nil),       // 3: events.v1.UserUpdatedPayload
	(*UserDeletedPayload)(nil),       // 4: events.v1.UserDeletedPayload
	(*PasswordChangedPayload)(nil),   // 5: events.v1.PasswordChangedPayload
	(*TenantCreatedPayload)(nil),     // 6: events.v1.TenantCreatedPayload
	(*TenantUpdatedPayload)(nil),     // 7: events.v1.TenantUpdatedPayload
	(*TenantSuspendedPayload)(nil),   // 8: events.v1.TenantSuspendedPayload
	(*RoleAssignedPayload)(nil),      // 9: events.v1.RoleAssignedPayload
	(*RoleRevokedPayload)(nil),       // 10: events.v1.RoleRevokedPayload
	(*PermissionChangedPayload)(nil), // 11: events.v1.PermissionChangedPayload
	(*SessionCreatedPayload)(nil),    // 12: events.v1.SessionCreatedPayload
	(*SessionExpiredPayload)(nil),    // 13: events.v1.SessionExpiredPayload
	(*TokenGeneratedPayload)(nil),    // 14: events.v1.TokenGeneratedPayload
	(*TokenRevokedPayload)(nil),      // 15: events.v1.TokenRevokedPayload
	(*SecurityEventPayload)(nil),     // 16: events.v1.SecurityEventPayload
	nil,                              // 17: events.v1.UserUpdatedPayload.OldValuesEntry
	nil,                              // 18: events.v1.UserUpdatedPayload.NewValuesEntry
	nil,                              // 19: events.v1.TenantUpdatedPayload.OldValuesEntry
	nil,                              // 20: events.v1.TenantUpdatedPayload.NewValuesEntry
	(*timestamppb.Timestamp)(nil),    // 21: google.protobuf.Timestamp
}
var file_api_proto_events_v1_identity_proto_depIdxs = []int32{
	21, // 0: events.v1.UserRegisteredPayload.registered_at:type_name -> google.protobuf.Timestamp
	21, // 1: events.v1.UserLoginPayload.login_at:type_name -> google.protobuf.Timestamp
	21, // 2: events.v1.UserLogoutPayload.logout_at:type_name -> google.protobuf.Timestamp
	17, // 3: events.v1.UserUpdatedPayload.old_values:type_name -> events.v1.UserUpdatedPayload.OldValuesEntry
	18, // 4: events.v1.UserUpdatedPayload.new_values:type_name -> events.v1.UserUpdatedPayload.NewValuesEntry
	21, // 5: events.v1.UserUpdatedPayload.updated_at:type_name -> google.protobuf.Timestamp
	21, // 6: events.v1.UserDeletedPayload.deleted_at:type_name -> google.protobuf.Timestamp
	21, // 7: events.v1.PasswordChangedPayload.changed_at:type_name -> google.protobuf.Timestamp
	21, // 8: events.v1.TenantCreatedPayload.created_at:type_name -> google.protobuf.Timestamp
	19, // 9: events.v1.TenantUpdatedPayload.old_values:type_name -> events.v1.TenantUpdatedPayload.OldValuesEntry
	20, // 10: events.v1.TenantUpdatedPayload.new_values:type_name -> events.v1.TenantUpdatedPayload.NewValuesEntry
	21, // 11: events.v1.TenantUpdatedPayload.updated_at:type_name -> google.protobuf.Timestamp
	21, // 12: events.v1.TenantSuspendedPayload.suspended_at:type_name -> google.protobuf.Timestamp
	21, // 13: events.v1.TenantSuspendedPayload.resume_at:type_name -> google.protobuf.Timestamp
	21, // 14: events.v1.RoleAssignedPayload.assigned_at:type_name -> google.protobuf.Timestamp
	21, // 15: events.v1.RoleRevokedPayload.revoked_at:type_name -> google.protobuf.Timestamp
	21, // 16: events.v1.PermissionChangedPayload.changed_at:type_name -> google.protobuf.Timestamp
	21, // 17: events.v1.SessionCreatedPayload.created_at:type_name -> google.protobuf.Timestamp
	21, // 18: events.v1.SessionExpiredPayload.expired_at:type_name -> google.protobuf.Timestamp
	21, // 19: events.v1.TokenGeneratedPayload.generated_at:type_name -> google.protobuf.Timestamp
	21, // 20: events.v1.TokenRevokedPayload.revoked_at:type_name -> google.protobuf.Timestamp
	21, // 21: events.v1.SecurityEventPayload.occurred_at:type_name -> google.protobuf.Timestamp
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_api_proto_events_v1_identity_proto_init() }
func file_api_proto_events_v1_identity_proto_init() {
	if File_api_proto_events_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_events_v1_identity_proto_rawDesc), len(file_api_proto_events_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_events_v1_identity_proto_goTypes,
		DependencyIndexes: file_api_proto_events_v1_identity_proto_depIdxs,
		MessageInfos:      file_api_proto_events_v1_identity_proto_msgTypes,
	}.Build()
	File_api_proto_events_v1_identity_proto = out.File
	file_api_proto_events_v1_identity_proto_goTypes = nil
	file_api_proto_events_v1_identity_proto_depIdxs = nil
}
