server:
  http:
    addr: 0.0.0.0:8000
    timeout: 10s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 10s

data:
  database:
    driver: postgres
    source: postgres://voicehelper:voicehelper_dev@localhost:5432/voicehelper?sslmode=disable
  redis:
    addr: localhost:6379
    read_timeout: 3s
    write_timeout: 3s
    db: 0

jwt_secret: "your-super-secret-jwt-key-change-this-in-production"

trace:
  endpoint: http://localhost:4318

