# Knowledge Service Configuration

server:
  http:
    network: tcp
    addr: 0.0.0.0:8000
    timeout: 30s
  grpc:
    network: tcp
    addr: 0.0.0.0:9000
    timeout: 30s

data:
  database:
    driver: postgres
    source: postgres://user:password@localhost:5432/knowledge?sslmode=disable

storage:
  endpoint: localhost:9000
  access_key_id: minioadmin
  secret_access_key: minioadmin
  bucket_name: knowledge-documents
  use_ssl: false

event:
  brokers:
    - localhost:9092
  topic: knowledge-events

security:
  clamav:
    host: localhost
    port: 3310
    timeout: 30s

observability:
  service_name: knowledge-service
  tracing:
    endpoint: http://localhost:14268/api/traces
    sample_rate: 0.1
  metrics:
    endpoint: http://localhost:9090
