server:
  http:
    addr: 0.0.0.0:8000
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s

data:
  database:
    driver: postgres
    source: postgres://voicehelper:voicehelper_dev@localhost:5432/voicehelper?sslmode=disable

trace:
  endpoint: http://localhost:4318

log:
  level: info
  format: json
