version: '3.8'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: voicehelper/notification-service:latest
    container_name: notification-service
    ports:
      - "9005:9005"  # gRPC port
      - "8005:8005"  # HTTP port
    environment:
      - ENV=development
      - LOG_LEVEL=info
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=voicehelper
      - POSTGRES_PASSWORD=voicehelper123
      - POSTGRES_DB=voicehelper
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - voicehelper-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: notification-postgres
    environment:
      - POSTGRES_USER=voicehelper
      - POSTGRES_PASSWORD=voicehelper123
      - POSTGRES_DB=voicehelper
    ports:
      - "5437:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../../migrations/postgres:/docker-entrypoint-initdb.d
    networks:
      - voicehelper-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: notification-redis
    ports:
      - "6384:6379"
    volumes:
      - redis-data:/data
    networks:
      - voicehelper-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  kafka:
    image: bitnami/kafka:latest
    container_name: notification-kafka
    ports:
      - "9095:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - voicehelper-network
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
  kafka-data:

networks:
  voicehelper-network:
    driver: bridge
