// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/conversation/v1/conversation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConversationMode int32

const (
	ConversationMode_CONVERSATION_MODE_UNSPECIFIED ConversationMode = 0
	ConversationMode_CONVERSATION_MODE_CHAT        ConversationMode = 1 // 普通对话
	ConversationMode_CONVERSATION_MODE_AGENT       ConversationMode = 2 // Agent 模式
	ConversationMode_CONVERSATION_MODE_WORKFLOW    ConversationMode = 3 // 工作流模式
	ConversationMode_CONVERSATION_MODE_VOICE       ConversationMode = 4 // 语音对话
)

// Enum value maps for ConversationMode.
var (
	ConversationMode_name = map[int32]string{
		0: "CONVERSATION_MODE_UNSPECIFIED",
		1: "CONVERSATION_MODE_CHAT",
		2: "CONVERSATION_MODE_AGENT",
		3: "CONVERSATION_MODE_WORKFLOW",
		4: "CONVERSATION_MODE_VOICE",
	}
	ConversationMode_value = map[string]int32{
		"CONVERSATION_MODE_UNSPECIFIED": 0,
		"CONVERSATION_MODE_CHAT":        1,
		"CONVERSATION_MODE_AGENT":       2,
		"CONVERSATION_MODE_WORKFLOW":    3,
		"CONVERSATION_MODE_VOICE":       4,
	}
)

func (x ConversationMode) Enum() *ConversationMode {
	p := new(ConversationMode)
	*p = x
	return p
}

func (x ConversationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_conversation_v1_conversation_proto_enumTypes[0].Descriptor()
}

func (ConversationMode) Type() protoreflect.EnumType {
	return &file_api_proto_conversation_v1_conversation_proto_enumTypes[0]
}

func (x ConversationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationMode.Descriptor instead.
func (ConversationMode) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{0}
}

type ConversationStatus int32

const (
	ConversationStatus_CONVERSATION_STATUS_UNSPECIFIED ConversationStatus = 0
	ConversationStatus_CONVERSATION_STATUS_ACTIVE      ConversationStatus = 1 // 活跃
	ConversationStatus_CONVERSATION_STATUS_ARCHIVED    ConversationStatus = 2 // 已归档
	ConversationStatus_CONVERSATION_STATUS_DELETED     ConversationStatus = 3 // 已删除
)

// Enum value maps for ConversationStatus.
var (
	ConversationStatus_name = map[int32]string{
		0: "CONVERSATION_STATUS_UNSPECIFIED",
		1: "CONVERSATION_STATUS_ACTIVE",
		2: "CONVERSATION_STATUS_ARCHIVED",
		3: "CONVERSATION_STATUS_DELETED",
	}
	ConversationStatus_value = map[string]int32{
		"CONVERSATION_STATUS_UNSPECIFIED": 0,
		"CONVERSATION_STATUS_ACTIVE":      1,
		"CONVERSATION_STATUS_ARCHIVED":    2,
		"CONVERSATION_STATUS_DELETED":     3,
	}
)

func (x ConversationStatus) Enum() *ConversationStatus {
	p := new(ConversationStatus)
	*p = x
	return p
}

func (x ConversationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_conversation_v1_conversation_proto_enumTypes[1].Descriptor()
}

func (ConversationStatus) Type() protoreflect.EnumType {
	return &file_api_proto_conversation_v1_conversation_proto_enumTypes[1]
}

func (x ConversationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationStatus.Descriptor instead.
func (ConversationStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{1}
}

type MessageRole int32

const (
	MessageRole_MESSAGE_ROLE_UNSPECIFIED MessageRole = 0
	MessageRole_MESSAGE_ROLE_USER        MessageRole = 1 // 用户消息
	MessageRole_MESSAGE_ROLE_ASSISTANT   MessageRole = 2 // 助手回复
	MessageRole_MESSAGE_ROLE_SYSTEM      MessageRole = 3 // 系统消息
	MessageRole_MESSAGE_ROLE_TOOL        MessageRole = 4 // 工具调用结果
)

// Enum value maps for MessageRole.
var (
	MessageRole_name = map[int32]string{
		0: "MESSAGE_ROLE_UNSPECIFIED",
		1: "MESSAGE_ROLE_USER",
		2: "MESSAGE_ROLE_ASSISTANT",
		3: "MESSAGE_ROLE_SYSTEM",
		4: "MESSAGE_ROLE_TOOL",
	}
	MessageRole_value = map[string]int32{
		"MESSAGE_ROLE_UNSPECIFIED": 0,
		"MESSAGE_ROLE_USER":        1,
		"MESSAGE_ROLE_ASSISTANT":   2,
		"MESSAGE_ROLE_SYSTEM":      3,
		"MESSAGE_ROLE_TOOL":        4,
	}
)

func (x MessageRole) Enum() *MessageRole {
	p := new(MessageRole)
	*p = x
	return p
}

func (x MessageRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageRole) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_conversation_v1_conversation_proto_enumTypes[2].Descriptor()
}

func (MessageRole) Type() protoreflect.EnumType {
	return &file_api_proto_conversation_v1_conversation_proto_enumTypes[2]
}

func (x MessageRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageRole.Descriptor instead.
func (MessageRole) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{2}
}

type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Mode          ConversationMode       `protobuf:"varint,5,opt,name=mode,proto3,enum=conversation.v1.ConversationMode" json:"mode,omitempty"`
	Status        ConversationStatus     `protobuf:"varint,6,opt,name=status,proto3,enum=conversation.v1.ConversationStatus" json:"status,omitempty"`
	Metadata      *ConversationMetadata  `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastMessageAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_message_at,json=lastMessageAt,proto3" json:"last_message_at,omitempty"`
	MessageCount  int32                  `protobuf:"varint,11,opt,name=message_count,json=messageCount,proto3" json:"message_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *Conversation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Conversation) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Conversation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Conversation) GetMode() ConversationMode {
	if x != nil {
		return x.Mode
	}
	return ConversationMode_CONVERSATION_MODE_UNSPECIFIED
}

func (x *Conversation) GetStatus() ConversationStatus {
	if x != nil {
		return x.Status
	}
	return ConversationStatus_CONVERSATION_STATUS_UNSPECIFIED
}

func (x *Conversation) GetMetadata() *ConversationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Conversation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Conversation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Conversation) GetLastMessageAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMessageAt
	}
	return nil
}

func (x *Conversation) GetMessageCount() int32 {
	if x != nil {
		return x.MessageCount
	}
	return 0
}

type ConversationMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                                                                             // 使用的模型
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`     // 标签
	Config        map[string]string      `protobuf:"bytes,3,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 配置项
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationMetadata) Reset() {
	*x = ConversationMetadata{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMetadata) ProtoMessage() {}

func (x *ConversationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMetadata.ProtoReflect.Descriptor instead.
func (*ConversationMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *ConversationMetadata) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ConversationMetadata) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ConversationMetadata) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type CreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Mode          ConversationMode       `protobuf:"varint,4,opt,name=mode,proto3,enum=conversation.v1.ConversationMode" json:"mode,omitempty"`
	Metadata      *ConversationMetadata  `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateConversationRequest) Reset() {
	*x = CreateConversationRequest{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConversationRequest) ProtoMessage() {}

func (x *CreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConversationRequest.ProtoReflect.Descriptor instead.
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateConversationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateConversationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateConversationRequest) GetMode() ConversationMode {
	if x != nil {
		return x.Mode
	}
	return ConversationMode_CONVERSATION_MODE_UNSPECIFIED
}

func (x *CreateConversationRequest) GetMetadata() *ConversationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用于权限校验
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationRequest) Reset() {
	*x = GetConversationRequest{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationRequest) ProtoMessage() {}

func (x *GetConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationRequest.ProtoReflect.Descriptor instead.
func (*GetConversationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *GetConversationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Mode          ConversationMode       `protobuf:"varint,3,opt,name=mode,proto3,enum=conversation.v1.ConversationMode" json:"mode,omitempty"` // 可选过滤
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *ListConversationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListConversationsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListConversationsRequest) GetMode() ConversationMode {
	if x != nil {
		return x.Mode
	}
	return ConversationMode_CONVERSATION_MODE_UNSPECIFIED
}

func (x *ListConversationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConversationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListConversationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Status        *ConversationStatus    `protobuf:"varint,4,opt,name=status,proto3,enum=conversation.v1.ConversationStatus,oneof" json:"status,omitempty"`
	Metadata      *ConversationMetadata  `protobuf:"bytes,5,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConversationRequest) Reset() {
	*x = UpdateConversationRequest{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConversationRequest) ProtoMessage() {}

func (x *UpdateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConversationRequest.ProtoReflect.Descriptor instead.
func (*UpdateConversationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateConversationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateConversationRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateConversationRequest) GetStatus() ConversationStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ConversationStatus_CONVERSATION_STATUS_UNSPECIFIED
}

func (x *UpdateConversationRequest) GetMetadata() *ConversationMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationRequest) Reset() {
	*x = DeleteConversationRequest{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationRequest) ProtoMessage() {}

func (x *DeleteConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationRequest.ProtoReflect.Descriptor instead.
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteConversationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteConversationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Role           MessageRole            `protobuf:"varint,3,opt,name=role,proto3,enum=conversation.v1.MessageRole" json:"role,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Metadata       *MessageMetadata       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{8}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Message) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetMetadata() *MessageMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type MessageMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`                                                                           // 使用的模型
	TokensUsed    int64                  `protobuf:"varint,2,opt,name=tokens_used,json=tokensUsed,proto3" json:"tokens_used,omitempty"`                                              // Token 消耗
	CostUsd       float32                `protobuf:"fixed32,3,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`                                                      // 成本（美元）
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`                                                 // 延迟（毫秒）
	Extra         map[string]string      `protobuf:"bytes,5,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 额外信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageMetadata) Reset() {
	*x = MessageMetadata{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageMetadata) ProtoMessage() {}

func (x *MessageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageMetadata.ProtoReflect.Descriptor instead.
func (*MessageMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{9}
}

func (x *MessageMetadata) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *MessageMetadata) GetTokensUsed() int64 {
	if x != nil {
		return x.TokensUsed
	}
	return 0
}

func (x *MessageMetadata) GetCostUsd() float32 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *MessageMetadata) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *MessageMetadata) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Role           MessageRole            `protobuf:"varint,4,opt,name=role,proto3,enum=conversation.v1.MessageRole" json:"role,omitempty"`
	Stream         bool                   `protobuf:"varint,5,opt,name=stream,proto3" json:"stream,omitempty"` // 是否流式返回
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{10}
}

func (x *SendMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SendMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

func (x *SendMessageRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

type GetMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{11}
}

func (x *GetMessageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

type ListMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                      // 限制返回数量（默认 50）
	BeforeId       string                 `protobuf:"bytes,4,opt,name=before_id,json=beforeId,proto3" json:"before_id,omitempty"` // 分页游标（消息 ID）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{12}
}

func (x *ListMessagesRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ListMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesRequest) GetBeforeId() string {
	if x != nil {
		return x.BeforeId
	}
	return ""
}

type ListMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessagesResponse) Reset() {
	*x = ListMessagesResponse{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesResponse) ProtoMessage() {}

func (x *ListMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListMessagesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{13}
}

func (x *ListMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListMessagesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// 流式消息块
type MessageChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ContentDelta   string                 `protobuf:"bytes,3,opt,name=content_delta,json=contentDelta,proto3" json:"content_delta,omitempty"` // 增量内容
	IsFinal        bool                   `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`               // 是否最后一块
	Metadata       *MessageMetadata       `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`                             // 仅在最后一块中返回
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageChunk) Reset() {
	*x = MessageChunk{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageChunk) ProtoMessage() {}

func (x *MessageChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageChunk.ProtoReflect.Descriptor instead.
func (*MessageChunk) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{14}
}

func (x *MessageChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageChunk) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageChunk) GetContentDelta() string {
	if x != nil {
		return x.ContentDelta
	}
	return ""
}

func (x *MessageChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *MessageChunk) GetMetadata() *MessageMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StreamMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content        string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamMessagesRequest) Reset() {
	*x = StreamMessagesRequest{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMessagesRequest) ProtoMessage() {}

func (x *StreamMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMessagesRequest.ProtoReflect.Descriptor instead.
func (*StreamMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{15}
}

func (x *StreamMessagesRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *StreamMessagesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StreamMessagesRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Context struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Messages       []*ContextMessage      `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`                                 // 历史消息
	MaxTokens      int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`             // 最大 Token 数
	CurrentTokens  int32                  `protobuf:"varint,4,opt,name=current_tokens,json=currentTokens,proto3" json:"current_tokens,omitempty"` // 当前 Token 数
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{16}
}

func (x *Context) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *Context) GetMessages() []*ContextMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Context) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *Context) GetCurrentTokens() int32 {
	if x != nil {
		return x.CurrentTokens
	}
	return 0
}

func (x *Context) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ContextMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          MessageRole            `protobuf:"varint,1,opt,name=role,proto3,enum=conversation.v1.MessageRole" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextMessage) Reset() {
	*x = ContextMessage{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextMessage) ProtoMessage() {}

func (x *ContextMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextMessage.ProtoReflect.Descriptor instead.
func (*ContextMessage) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{17}
}

func (x *ContextMessage) GetRole() MessageRole {
	if x != nil {
		return x.Role
	}
	return MessageRole_MESSAGE_ROLE_UNSPECIFIED
}

func (x *ContextMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type GetContextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetContextRequest) Reset() {
	*x = GetContextRequest{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextRequest) ProtoMessage() {}

func (x *GetContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextRequest.ProtoReflect.Descriptor instead.
func (*GetContextRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{18}
}

func (x *GetContextRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *GetContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateContextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Messages       []*ContextMessage      `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateContextRequest) Reset() {
	*x = UpdateContextRequest{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContextRequest) ProtoMessage() {}

func (x *UpdateContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContextRequest.ProtoReflect.Descriptor instead.
func (*UpdateContextRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateContextRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *UpdateContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateContextRequest) GetMessages() []*ContextMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type ClearContextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClearContextRequest) Reset() {
	*x = ClearContextRequest{}
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearContextRequest) ProtoMessage() {}

func (x *ClearContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_conversation_v1_conversation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearContextRequest.ProtoReflect.Descriptor instead.
func (*ClearContextRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_conversation_v1_conversation_proto_rawDescGZIP(), []int{20}
}

func (x *ClearContextRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ClearContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_api_proto_conversation_v1_conversation_proto protoreflect.FileDescriptor

const file_api_proto_conversation_v1_conversation_proto_rawDesc = "" +
	"\n" +
	",api/proto/conversation/v1/conversation.proto\x12\x0fconversation.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x04\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x125\n" +
	"\x04mode\x18\x05 \x01(\x0e2!.conversation.v1.ConversationModeR\x04mode\x12;\n" +
	"\x06status\x18\x06 \x01(\x0e2#.conversation.v1.ConversationStatusR\x06status\x12A\n" +
	"\bmetadata\x18\a \x01(\v2%.conversation.v1.ConversationMetadataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12B\n" +
	"\x0flast_message_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rlastMessageAt\x12#\n" +
	"\rmessage_count\x18\v \x01(\x05R\fmessageCount\"\xb0\x02\n" +
	"\x14ConversationMetadata\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12C\n" +
	"\x04tags\x18\x02 \x03(\v2/.conversation.v1.ConversationMetadata.TagsEntryR\x04tags\x12I\n" +
	"\x06config\x18\x03 \x03(\v21.conversation.v1.ConversationMetadata.ConfigEntryR\x06config\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe1\x01\n" +
	"\x19CreateConversationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x125\n" +
	"\x04mode\x18\x04 \x01(\x0e2!.conversation.v1.ConversationModeR\x04mode\x12A\n" +
	"\bmetadata\x18\x05 \x01(\v2%.conversation.v1.ConversationMetadataR\bmetadata\"A\n" +
	"\x16GetConversationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xb8\x01\n" +
	"\x18ListConversationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x125\n" +
	"\x04mode\x18\x03 \x01(\x0e2!.conversation.v1.ConversationModeR\x04mode\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"v\n" +
	"\x19ListConversationsResponse\x12C\n" +
	"\rconversations\x18\x01 \x03(\v2\x1d.conversation.v1.ConversationR\rconversations\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8b\x02\n" +
	"\x19UpdateConversationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12@\n" +
	"\x06status\x18\x04 \x01(\x0e2#.conversation.v1.ConversationStatusH\x01R\x06status\x88\x01\x01\x12F\n" +
	"\bmetadata\x18\x05 \x01(\v2%.conversation.v1.ConversationMetadataH\x02R\bmetadata\x88\x01\x01B\b\n" +
	"\x06_titleB\t\n" +
	"\a_statusB\v\n" +
	"\t_metadata\"D\n" +
	"\x19DeleteConversationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x87\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x120\n" +
	"\x04role\x18\x03 \x01(\x0e2\x1c.conversation.v1.MessageRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12<\n" +
	"\bmetadata\x18\x05 \x01(\v2 .conversation.v1.MessageMetadataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xff\x01\n" +
	"\x0fMessageMetadata\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1f\n" +
	"\vtokens_used\x18\x02 \x01(\x03R\n" +
	"tokensUsed\x12\x19\n" +
	"\bcost_usd\x18\x03 \x01(\x02R\acostUsd\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\x12A\n" +
	"\x05extra\x18\x05 \x03(\v2+.conversation.v1.MessageMetadata.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x01\n" +
	"\x12SendMessageRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x120\n" +
	"\x04role\x18\x04 \x01(\x0e2\x1c.conversation.v1.MessageRoleR\x04role\x12\x16\n" +
	"\x06stream\x18\x05 \x01(\bR\x06stream\"L\n" +
	"\x11GetMessageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\"\x8a\x01\n" +
	"\x13ListMessagesRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tbefore_id\x18\x04 \x01(\tR\bbeforeId\"\x88\x01\n" +
	"\x14ListMessagesResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.conversation.v1.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\"\xc5\x01\n" +
	"\fMessageChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12#\n" +
	"\rcontent_delta\x18\x03 \x01(\tR\fcontentDelta\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal\x12<\n" +
	"\bmetadata\x18\x05 \x01(\v2 .conversation.v1.MessageMetadataR\bmetadata\"s\n" +
	"\x15StreamMessagesRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"\xf0\x01\n" +
	"\aContext\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12;\n" +
	"\bmessages\x18\x02 \x03(\v2\x1f.conversation.v1.ContextMessageR\bmessages\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\x12%\n" +
	"\x0ecurrent_tokens\x18\x04 \x01(\x05R\rcurrentTokens\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\\\n" +
	"\x0eContextMessage\x120\n" +
	"\x04role\x18\x01 \x01(\x0e2\x1c.conversation.v1.MessageRoleR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"U\n" +
	"\x11GetContextRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x95\x01\n" +
	"\x14UpdateContextRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12;\n" +
	"\bmessages\x18\x03 \x03(\v2\x1f.conversation.v1.ContextMessageR\bmessages\"W\n" +
	"\x13ClearContextRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId*\xab\x01\n" +
	"\x10ConversationMode\x12!\n" +
	"\x1dCONVERSATION_MODE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CONVERSATION_MODE_CHAT\x10\x01\x12\x1b\n" +
	"\x17CONVERSATION_MODE_AGENT\x10\x02\x12\x1e\n" +
	"\x1aCONVERSATION_MODE_WORKFLOW\x10\x03\x12\x1b\n" +
	"\x17CONVERSATION_MODE_VOICE\x10\x04*\x9c\x01\n" +
	"\x12ConversationStatus\x12#\n" +
	"\x1fCONVERSATION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONVERSATION_STATUS_ACTIVE\x10\x01\x12 \n" +
	"\x1cCONVERSATION_STATUS_ARCHIVED\x10\x02\x12\x1f\n" +
	"\x1bCONVERSATION_STATUS_DELETED\x10\x03*\x8e\x01\n" +
	"\vMessageRole\x12\x1c\n" +
	"\x18MESSAGE_ROLE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MESSAGE_ROLE_USER\x10\x01\x12\x1a\n" +
	"\x16MESSAGE_ROLE_ASSISTANT\x10\x02\x12\x17\n" +
	"\x13MESSAGE_ROLE_SYSTEM\x10\x03\x12\x15\n" +
	"\x11MESSAGE_ROLE_TOOL\x10\x042\xb6\b\n" +
	"\x13ConversationService\x12_\n" +
	"\x12CreateConversation\x12*.conversation.v1.CreateConversationRequest\x1a\x1d.conversation.v1.Conversation\x12Y\n" +
	"\x0fGetConversation\x12'.conversation.v1.GetConversationRequest\x1a\x1d.conversation.v1.Conversation\x12j\n" +
	"\x11ListConversations\x12).conversation.v1.ListConversationsRequest\x1a*.conversation.v1.ListConversationsResponse\x12_\n" +
	"\x12UpdateConversation\x12*.conversation.v1.UpdateConversationRequest\x1a\x1d.conversation.v1.Conversation\x12X\n" +
	"\x12DeleteConversation\x12*.conversation.v1.DeleteConversationRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\vSendMessage\x12#.conversation.v1.SendMessageRequest\x1a\x18.conversation.v1.Message\x12J\n" +
	"\n" +
	"GetMessage\x12\".conversation.v1.GetMessageRequest\x1a\x18.conversation.v1.Message\x12[\n" +
	"\fListMessages\x12$.conversation.v1.ListMessagesRequest\x1a%.conversation.v1.ListMessagesResponse\x12Y\n" +
	"\x0eStreamMessages\x12&.conversation.v1.StreamMessagesRequest\x1a\x1d.conversation.v1.MessageChunk0\x01\x12J\n" +
	"\n" +
	"GetContext\x12\".conversation.v1.GetContextRequest\x1a\x18.conversation.v1.Context\x12P\n" +
	"\rUpdateContext\x12%.conversation.v1.UpdateContextRequest\x1a\x18.conversation.v1.Context\x12L\n" +
	"\fClearContext\x12$.conversation.v1.ClearContextRequest\x1a\x16.google.protobuf.EmptyB*Z(voicehelper/api/proto/conversation/v1;v1b\x06proto3"

var (
	file_api_proto_conversation_v1_conversation_proto_rawDescOnce sync.Once
	file_api_proto_conversation_v1_conversation_proto_rawDescData []byte
)

func file_api_proto_conversation_v1_conversation_proto_rawDescGZIP() []byte {
	file_api_proto_conversation_v1_conversation_proto_rawDescOnce.Do(func() {
		file_api_proto_conversation_v1_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_conversation_v1_conversation_proto_rawDesc), len(file_api_proto_conversation_v1_conversation_proto_rawDesc)))
	})
	return file_api_proto_conversation_v1_conversation_proto_rawDescData
}

var file_api_proto_conversation_v1_conversation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_conversation_v1_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_proto_conversation_v1_conversation_proto_goTypes = []any{
	(ConversationMode)(0),             // 0: conversation.v1.ConversationMode
	(ConversationStatus)(0),           // 1: conversation.v1.ConversationStatus
	(MessageRole)(0),                  // 2: conversation.v1.MessageRole
	(*Conversation)(nil),              // 3: conversation.v1.Conversation
	(*ConversationMetadata)(nil),      // 4: conversation.v1.ConversationMetadata
	(*CreateConversationRequest)(nil), // 5: conversation.v1.CreateConversationRequest
	(*GetConversationRequest)(nil),    // 6: conversation.v1.GetConversationRequest
	(*ListConversationsRequest)(nil),  // 7: conversation.v1.ListConversationsRequest
	(*ListConversationsResponse)(nil), // 8: conversation.v1.ListConversationsResponse
	(*UpdateConversationRequest)(nil), // 9: conversation.v1.UpdateConversationRequest
	(*DeleteConversationRequest)(nil), // 10: conversation.v1.DeleteConversationRequest
	(*Message)(nil),                   // 11: conversation.v1.Message
	(*MessageMetadata)(nil),           // 12: conversation.v1.MessageMetadata
	(*SendMessageRequest)(nil),        // 13: conversation.v1.SendMessageRequest
	(*GetMessageRequest)(nil),         // 14: conversation.v1.GetMessageRequest
	(*ListMessagesRequest)(nil),       // 15: conversation.v1.ListMessagesRequest
	(*ListMessagesResponse)(nil),      // 16: conversation.v1.ListMessagesResponse
	(*MessageChunk)(nil),              // 17: conversation.v1.MessageChunk
	(*StreamMessagesRequest)(nil),     // 18: conversation.v1.StreamMessagesRequest
	(*Context)(nil),                   // 19: conversation.v1.Context
	(*ContextMessage)(nil),            // 20: conversation.v1.ContextMessage
	(*GetContextRequest)(nil),         // 21: conversation.v1.GetContextRequest
	(*UpdateContextRequest)(nil),      // 22: conversation.v1.UpdateContextRequest
	(*ClearContextRequest)(nil),       // 23: conversation.v1.ClearContextRequest
	nil,                               // 24: conversation.v1.ConversationMetadata.TagsEntry
	nil,                               // 25: conversation.v1.ConversationMetadata.ConfigEntry
	nil,                               // 26: conversation.v1.MessageMetadata.ExtraEntry
	(*timestamppb.Timestamp)(nil),     // 27: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),             // 28: google.protobuf.Empty
}
var file_api_proto_conversation_v1_conversation_proto_depIdxs = []int32{
	0,  // 0: conversation.v1.Conversation.mode:type_name -> conversation.v1.ConversationMode
	1,  // 1: conversation.v1.Conversation.status:type_name -> conversation.v1.ConversationStatus
	4,  // 2: conversation.v1.Conversation.metadata:type_name -> conversation.v1.ConversationMetadata
	27, // 3: conversation.v1.Conversation.created_at:type_name -> google.protobuf.Timestamp
	27, // 4: conversation.v1.Conversation.updated_at:type_name -> google.protobuf.Timestamp
	27, // 5: conversation.v1.Conversation.last_message_at:type_name -> google.protobuf.Timestamp
	24, // 6: conversation.v1.ConversationMetadata.tags:type_name -> conversation.v1.ConversationMetadata.TagsEntry
	25, // 7: conversation.v1.ConversationMetadata.config:type_name -> conversation.v1.ConversationMetadata.ConfigEntry
	0,  // 8: conversation.v1.CreateConversationRequest.mode:type_name -> conversation.v1.ConversationMode
	4,  // 9: conversation.v1.CreateConversationRequest.metadata:type_name -> conversation.v1.ConversationMetadata
	0,  // 10: conversation.v1.ListConversationsRequest.mode:type_name -> conversation.v1.ConversationMode
	3,  // 11: conversation.v1.ListConversationsResponse.conversations:type_name -> conversation.v1.Conversation
	1,  // 12: conversation.v1.UpdateConversationRequest.status:type_name -> conversation.v1.ConversationStatus
	4,  // 13: conversation.v1.UpdateConversationRequest.metadata:type_name -> conversation.v1.ConversationMetadata
	2,  // 14: conversation.v1.Message.role:type_name -> conversation.v1.MessageRole
	12, // 15: conversation.v1.Message.metadata:type_name -> conversation.v1.MessageMetadata
	27, // 16: conversation.v1.Message.created_at:type_name -> google.protobuf.Timestamp
	26, // 17: conversation.v1.MessageMetadata.extra:type_name -> conversation.v1.MessageMetadata.ExtraEntry
	2,  // 18: conversation.v1.SendMessageRequest.role:type_name -> conversation.v1.MessageRole
	11, // 19: conversation.v1.ListMessagesResponse.messages:type_name -> conversation.v1.Message
	12, // 20: conversation.v1.MessageChunk.metadata:type_name -> conversation.v1.MessageMetadata
	20, // 21: conversation.v1.Context.messages:type_name -> conversation.v1.ContextMessage
	27, // 22: conversation.v1.Context.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 23: conversation.v1.ContextMessage.role:type_name -> conversation.v1.MessageRole
	20, // 24: conversation.v1.UpdateContextRequest.messages:type_name -> conversation.v1.ContextMessage
	5,  // 25: conversation.v1.ConversationService.CreateConversation:input_type -> conversation.v1.CreateConversationRequest
	6,  // 26: conversation.v1.ConversationService.GetConversation:input_type -> conversation.v1.GetConversationRequest
	7,  // 27: conversation.v1.ConversationService.ListConversations:input_type -> conversation.v1.ListConversationsRequest
	9,  // 28: conversation.v1.ConversationService.UpdateConversation:input_type -> conversation.v1.UpdateConversationRequest
	10, // 29: conversation.v1.ConversationService.DeleteConversation:input_type -> conversation.v1.DeleteConversationRequest
	13, // 30: conversation.v1.ConversationService.SendMessage:input_type -> conversation.v1.SendMessageRequest
	14, // 31: conversation.v1.ConversationService.GetMessage:input_type -> conversation.v1.GetMessageRequest
	15, // 32: conversation.v1.ConversationService.ListMessages:input_type -> conversation.v1.ListMessagesRequest
	18, // 33: conversation.v1.ConversationService.StreamMessages:input_type -> conversation.v1.StreamMessagesRequest
	21, // 34: conversation.v1.ConversationService.GetContext:input_type -> conversation.v1.GetContextRequest
	22, // 35: conversation.v1.ConversationService.UpdateContext:input_type -> conversation.v1.UpdateContextRequest
	23, // 36: conversation.v1.ConversationService.ClearContext:input_type -> conversation.v1.ClearContextRequest
	3,  // 37: conversation.v1.ConversationService.CreateConversation:output_type -> conversation.v1.Conversation
	3,  // 38: conversation.v1.ConversationService.GetConversation:output_type -> conversation.v1.Conversation
	8,  // 39: conversation.v1.ConversationService.ListConversations:output_type -> conversation.v1.ListConversationsResponse
	3,  // 40: conversation.v1.ConversationService.UpdateConversation:output_type -> conversation.v1.Conversation
	28, // 41: conversation.v1.ConversationService.DeleteConversation:output_type -> google.protobuf.Empty
	11, // 42: conversation.v1.ConversationService.SendMessage:output_type -> conversation.v1.Message
	11, // 43: conversation.v1.ConversationService.GetMessage:output_type -> conversation.v1.Message
	16, // 44: conversation.v1.ConversationService.ListMessages:output_type -> conversation.v1.ListMessagesResponse
	17, // 45: conversation.v1.ConversationService.StreamMessages:output_type -> conversation.v1.MessageChunk
	19, // 46: conversation.v1.ConversationService.GetContext:output_type -> conversation.v1.Context
	19, // 47: conversation.v1.ConversationService.UpdateContext:output_type -> conversation.v1.Context
	28, // 48: conversation.v1.ConversationService.ClearContext:output_type -> google.protobuf.Empty
	37, // [37:49] is the sub-list for method output_type
	25, // [25:37] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_api_proto_conversation_v1_conversation_proto_init() }
func file_api_proto_conversation_v1_conversation_proto_init() {
	if File_api_proto_conversation_v1_conversation_proto != nil {
		return
	}
	file_api_proto_conversation_v1_conversation_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_conversation_v1_conversation_proto_rawDesc), len(file_api_proto_conversation_v1_conversation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_conversation_v1_conversation_proto_goTypes,
		DependencyIndexes: file_api_proto_conversation_v1_conversation_proto_depIdxs,
		EnumInfos:         file_api_proto_conversation_v1_conversation_proto_enumTypes,
		MessageInfos:      file_api_proto_conversation_v1_conversation_proto_msgTypes,
	}.Build()
	File_api_proto_conversation_v1_conversation_proto = out.File
	file_api_proto_conversation_v1_conversation_proto_goTypes = nil
	file_api_proto_conversation_v1_conversation_proto_depIdxs = nil
}
