---
# Alertmanager 告警管理
# 接收 Prometheus 告警并路由到不同渠道
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: voiceassistant-infra
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alerts@voiceassistant.com'
      smtp_auth_username: 'alerts@voiceassistant.com'
      smtp_auth_password: 'password'
      smtp_require_tls: true

    # 告警路由
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'default'
      routes:
      # Critical 告警路由到多个渠道
      - match:
          severity: critical
        receiver: 'critical-alerts'
        continue: true

      # 数据库相关告警
      - match_re:
          service: (postgres|redis|milvus)
        receiver: 'database-team'

      # AI 服务告警
      - match_re:
          component: ai-engine
        receiver: 'ai-team'

    # 接收器配置
    receivers:
    - name: 'default'
      webhook_configs:
      - url: 'http://notification-service.voiceassistant-prod:9006/webhook/alerts'

    - name: 'critical-alerts'
      email_configs:
      - to: 'oncall@voiceassistant.com'
        headers:
          Subject: '[CRITICAL] VoiceAssistant Alert'
      webhook_configs:
      - url: 'http://notification-service.voiceassistant-prod:9006/webhook/critical'
      # 可选：集成钉钉/企业微信/Slack
      # webhook_configs:
      # - url: 'https://oapi.dingtalk.com/robot/send?access_token=xxx'

    - name: 'database-team'
      email_configs:
      - to: 'db-team@voiceassistant.com'
      webhook_configs:
      - url: 'http://notification-service.voiceassistant-prod:9006/webhook/database'

    - name: 'ai-team'
      email_configs:
      - to: 'ai-team@voiceassistant.com'
      webhook_configs:
      - url: 'http://notification-service.voiceassistant-prod:9006/webhook/ai'

    # 告警抑制规则
    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']

    - source_match:
        alertname: 'ServiceDown'
      target_match_re:
        alertname: '(HighLatency|HighErrorRate)'
      equal: ['service']

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: voiceassistant-infra
  labels:
    app: alertmanager
spec:
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: 9093
      name: web
  selector:
    app: alertmanager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: voiceassistant-infra
  labels:
    app: alertmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.26.0
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
            - "--cluster.listen-address=0.0.0.0:9094"
            - "--cluster.peer=alertmanager-0.alertmanager:9094"
            - "--cluster.peer=alertmanager-1.alertmanager:9094"
          ports:
            - containerPort: 9093
              name: web
            - containerPort: 9094
              name: cluster
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager
            - name: alertmanager-data
              mountPath: /alertmanager
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9093
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9093
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
        - name: alertmanager-data
          emptyDir: {}
