---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-config
  namespace: voiceassistant-infra
  labels:
    app: nacos
data:
  MODE: "cluster"
  NACOS_SERVERS: "nacos-0.nacos-headless:8848 nacos-1.nacos-headless:8848 nacos-2.nacos-headless:8848"
  PREFER_HOST_MODE: "hostname"
  SPRING_DATASOURCE_PLATFORM: "mysql"
  MYSQL_SERVICE_HOST: "mysql.voiceassistant-infra.svc.cluster.local"
  MYSQL_SERVICE_PORT: "3306"
  MYSQL_SERVICE_DB_NAME: "nacos"

---
apiVersion: v1
kind: Secret
metadata:
  name: nacos-secret
  namespace: voiceassistant-infra
type: Opaque
stringData:
  MYSQL_SERVICE_USER: "nacos"
  MYSQL_SERVICE_PASSWORD: "nacos"

---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: voiceassistant-infra
  labels:
    app: nacos
spec:
  clusterIP: None
  ports:
  - port: 8848
    name: server
    targetPort: 8848
  - port: 9848
    name: client-rpc
    targetPort: 9848
  - port: 9849
    name: raft-rpc
    targetPort: 9849
  - port: 7848
    name: old-raft-rpc
    targetPort: 7848
  selector:
    app: nacos

---
apiVersion: v1
kind: Service
metadata:
  name: nacos
  namespace: voiceassistant-infra
  labels:
    app: nacos
spec:
  type: ClusterIP
  ports:
  - port: 8848
    name: server
    targetPort: 8848
  - port: 9848
    name: client-rpc
    targetPort: 9848
  selector:
    app: nacos

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: voiceassistant-infra
  labels:
    app: nacos
spec:
  serviceName: nacos-headless
  replicas: 3
  selector:
    matchLabels:
      app: nacos
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nacos
            topologyKey: kubernetes.io/hostname
      initContainers:
      - name: peer-finder-plugin-install
        image: nacos/nacos-peer-finder-plugin:1.1
        imagePullPolicy: Always
        volumeMounts:
        - name: data
          mountPath: /home/nacos/plugins/peer-finder
          subPath: peer-finder
      containers:
      - name: nacos
        image: nacos/nacos-server:v2.2.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8848
          name: server
        - containerPort: 9848
          name: client-rpc
        - containerPort: 9849
          name: raft-rpc
        - containerPort: 7848
          name: old-raft-rpc
        envFrom:
        - configMapRef:
            name: nacos-config
        env:
        - name: NACOS_SERVER_PORT
          value: "8848"
        - name: NACOS_APPLICATION_PORT
          value: "8848"
        - name: NACOS_REPLICAS
          value: "3"
        - name: MYSQL_SERVICE_USER
          valueFrom:
            secretKeyRef:
              name: nacos-secret
              key: MYSQL_SERVICE_USER
        - name: MYSQL_SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nacos-secret
              key: MYSQL_SERVICE_PASSWORD
        - name: NACOS_SERVER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NACOS_SERVERS
          value: "nacos-0.nacos-headless.voiceassistant-infra.svc.cluster.local:8848 nacos-1.nacos-headless.voiceassistant-infra.svc.cluster.local:8848 nacos-2.nacos-headless.voiceassistant-infra.svc.cluster.local:8848"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /nacos/actuator/health
            port: 8848
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /nacos/actuator/health
            port: 8848
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        volumeMounts:
        - name: data
          mountPath: /home/nacos/plugins/peer-finder
          subPath: peer-finder
        - name: data
          mountPath: /home/nacos/data
          subPath: data
        - name: data
          mountPath: /home/nacos/logs
          subPath: logs
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

---
# MySQL for Nacos
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: voiceassistant-infra
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: voiceassistant-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "nacos"
        - name: MYSQL_USER
          value: "nacos"
        - name: MYSQL_PASSWORD
          value: "nacos"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: voiceassistant-infra
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

