# VoiceAssistant Helm Values

global:
  namespace: voiceassistant
  environment: production
  imageRegistry: ghcr.io/voiceassistant
  imagePullSecrets:
    - name: ghcr-secret

# ===== Go Services =====

identity-service:
  enabled: true
  replicaCount: 3
  image:
    repository: identity-service
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    grpcPort: 9000
    httpPort: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10
    targetCPUUtilizationPercentage: 70
  healthCheck:
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 10
      periodSeconds: 5

conversation-service:
  enabled: true
  replicaCount: 3
  image:
    repository: conversation-service
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 15
    targetCPUUtilizationPercentage: 70

knowledge-service:
  enabled: true
  replicaCount: 2
  image:
    repository: knowledge-service
    tag: "1.0.0"
  service:
    type: ClusterIP
    grpcPort: 9000
    httpPort: 8080
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

ai-orchestrator:
  enabled: true
  replicaCount: 3
  image:
    repository: ai-orchestrator
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 9003
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 20

model-router:
  enabled: true
  replicaCount: 2
  image:
    repository: model-router
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 9004
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

notification-service:
  enabled: true
  replicaCount: 2
  image:
    repository: notification-service
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 9006
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# ===== Python Services =====

agent-engine:
  enabled: true
  replicaCount: 3
  image:
    repository: agent-engine
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 8003
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10

rag-engine:
  enabled: true
  replicaCount: 3
  image:
    repository: rag-engine
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 8006
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 15

retrieval-service:
  enabled: true
  replicaCount: 3
  image:
    repository: retrieval-service
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 8012
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10

indexing-service:
  enabled: true
  replicaCount: 2
  image:
    repository: indexing-service
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 8004
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

model-adapter:
  enabled: true
  replicaCount: 3
  image:
    repository: model-adapter
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 8005
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 10

vector-store-adapter:
  enabled: true
  replicaCount: 2
  image:
    repository: vector-store-adapter
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 8003
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

voice-engine:
  enabled: true
  replicaCount: 2
  image:
    repository: voice-engine
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 8002
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi

multimodal-engine:
  enabled: true
  replicaCount: 2
  image:
    repository: multimodal-engine
    tag: "1.0.0"
  service:
    type: ClusterIP
    port: 8007
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

# ===== Infrastructure Services =====

postgresql:
  enabled: true
  auth:
    username: voiceassistant
    password: changeme
    database: voiceassistant
  primary:
    persistence:
      enabled: true
      size: 50Gi
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi

redis:
  enabled: true
  auth:
    enabled: true
    password: changeme
  master:
    persistence:
      enabled: true
      size: 10Gi
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

consul:
  enabled: true
  global:
    name: consul
    datacenter: dc1
  server:
    replicas: 3
    storage: 10Gi
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

# ===== API Gateway =====

apisix:
  enabled: true
  replicaCount: 3
  service:
    type: LoadBalancer
    http:
      enabled: true
      servicePort: 80
      containerPort: 9080
    tls:
      enabled: true
      servicePort: 443
      containerPort: 9443
  resources:
    limits:
      cpu: 2000m
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi

# ===== Observability =====

prometheus:
  enabled: true
  retention: 15d
  storage: 100Gi

grafana:
  enabled: true
  adminPassword: changeme

jaeger:
  enabled: true
  storage:
    type: elasticsearch
    elasticsearch:
      host: elasticsearch
      port: 9200

# ===== Security =====

serviceAccount:
  create: true
  name: voiceassistant-sa

networkPolicy:
  enabled: true
  policyTypes:
    - Ingress
    - Egress

podSecurityPolicy:
  enabled: true
