version: '3.8'

services:
  knowledge-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: voiceassistant/knowledge-service:latest
    container_name: knowledge-service
    ports:
      - "9002:9002"  # gRPC port
      - "8002:8002"  # HTTP port
    environment:
      - ENV=development
      - LOG_LEVEL=info
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=voiceassistant
      - POSTGRES_PASSWORD=voiceassistant123
      - POSTGRES_DB=voiceassistant
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - KAFKA_BROKERS=kafka:9092
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - postgres
      - redis
      - minio
      - kafka
    networks:
      - voiceassistant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: knowledge-postgres
    environment:
      - POSTGRES_USER=voiceassistant
      - POSTGRES_PASSWORD=voiceassistant123
      - POSTGRES_DB=voiceassistant
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../../migrations/postgres:/docker-entrypoint-initdb.d
    networks:
      - voiceassistant-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: knowledge-redis
    ports:
      - "6381:6379"
    volumes:
      - redis-data:/data
    networks:
      - voiceassistant-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  minio:
    image: minio/minio:latest
    container_name: knowledge-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    networks:
      - voiceassistant-network
    restart: unless-stopped
    command: server /data --console-address ":9001"

  kafka:
    image: bitnami/kafka:latest
    container_name: knowledge-kafka
    ports:
      - "9093:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - voiceassistant-network
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:
  minio-data:
  kafka-data:

networks:
  voiceassistant-network:
    driver: bridge
