---
# Destination Rules - 流量策略和负载均衡
# Identity Service
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: identity-service
  namespace: voiceassistant-prod
spec:
  host: identity-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: "x-user-id"  # 基于用户ID的会话亲和性
    connectionPool:
      tcp:
        maxConnections: 1000
      http:
        http1MaxPendingRequests: 1024
        http2MaxRequests: 1024
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
  subsets:
  - name: v1
    labels:
      version: v1

---
# Conversation Service
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: conversation-service
  namespace: voiceassistant-prod
spec:
  host: conversation-service
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: "x-conversation-id"
    connectionPool:
      tcp:
        maxConnections: 2000
      http:
        http1MaxPendingRequests: 2048
        http2MaxRequests: 2048
    outlierDetection:
      consecutiveErrors: 3
      interval: 20s
      baseEjectionTime: 30s
  subsets:
  - name: v1
    labels:
      version: v1

---
# AI Orchestrator
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: ai-orchestrator
  namespace: voiceassistant-prod
spec:
  host: ai-orchestrator
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST  # 最少请求负载均衡
    connectionPool:
      tcp:
        maxConnections: 500
      http:
        http2MaxRequests: 500
        maxRequestsPerConnection: 5
    outlierDetection:
      consecutiveErrors: 2
      interval: 10s
      baseEjectionTime: 60s
  subsets:
  - name: v1
    labels:
      version: v1

---
# Agent Engine
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: agent-engine
  namespace: voiceassistant-prod
spec:
  host: agent-engine
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
    connectionPool:
      tcp:
        maxConnections: 300
      http:
        http1MaxPendingRequests: 512
        http2MaxRequests: 512
        maxRequestsPerConnection: 3
    outlierDetection:
      consecutiveErrors: 3
      interval: 20s
      baseEjectionTime: 60s
  subsets:
  - name: v1
    labels:
      version: v1

---
# RAG Engine
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: rag-engine
  namespace: voiceassistant-prod
spec:
  host: rag-engine
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 500
      http:
        http1MaxPendingRequests: 1024
        http2MaxRequests: 1024
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 30s
  subsets:
  - name: v1
    labels:
      version: v1

---
# Model Adapter
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: model-adapter
  namespace: voiceassistant-prod
spec:
  host: model-adapter
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
    connectionPool:
      tcp:
        maxConnections: 400
      http:
        http1MaxPendingRequests: 512
        http2MaxRequests: 512
        maxRequestsPerConnection: 5
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 120s  # LLM调用可能偶尔超时
  subsets:
  - name: v1
    labels:
      version: v1

---
# Voice Engine
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: voice-engine
  namespace: voiceassistant-prod
spec:
  host: voice-engine
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: "x-session-id"  # WebSocket会话保持
    connectionPool:
      tcp:
        maxConnections: 1000
      http:
        http1MaxPendingRequests: 1024
        maxRequestsPerConnection: 1  # WebSocket长连接
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 30s
  subsets:
  - name: v1
    labels:
      version: v1

---
# Retrieval Service
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: retrieval-service
  namespace: voiceassistant-prod
spec:
  host: retrieval-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 600
      http:
        http1MaxPendingRequests: 1024
        http2MaxRequests: 1024
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 30s
  subsets:
  - name: v1
    labels:
      version: v1

---
# Model Router
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: model-router
  namespace: voiceassistant-prod
spec:
  host: model-router
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
    connectionPool:
      tcp:
        maxConnections: 500
      http:
        http1MaxPendingRequests: 1024
        http2MaxRequests: 1024
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 60s
  subsets:
  - name: v1
    labels:
      version: v1

---
# Knowledge Service
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: knowledge-service
  namespace: voiceassistant-prod
spec:
  host: knowledge-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 500
      http:
        http1MaxPendingRequests: 1024
        http2MaxRequests: 1024
    outlierDetection:
      consecutiveErrors: 3
      interval: 30s
      baseEjectionTime: 30s
  subsets:
  - name: v1
    labels:
      version: v1

