global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'voiceassistant'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yaml"

scrape_configs:
  # APISIX Gateway
  - job_name: 'apisix'
    static_configs:
      - targets: ['apisix:9091']

  # Go Services
  - job_name: 'identity-service'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: identity-service
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__

  - job_name: 'conversation-service'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: conversation-service

  # Python Services
  - job_name: 'agent-engine'
    static_configs:
      - targets: ['agent-engine:8001']

  - job_name: 'rag-engine'
    static_configs:
      - targets: ['rag-engine:8002']

  # Infrastructure
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'milvus'
    static_configs:
      - targets: ['milvus:9091']

