apiVersion: v1
kind: Namespace
metadata:
  name: voiceassistant-prod
  labels:
    name: voiceassistant-prod
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: voiceassistant-dev
  labels:
    name: voiceassistant-dev
    environment: development

