---
# 如果使用PostHog云服务而不是自托管，只需要配置Secret和ConfigMap
# 无需部署PostHog的PostgreSQL、Redis、ClickHouse等组件

# Model Router ConfigMap (云服务配置)
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-router-config-cloud
  namespace: voiceassistant-prod
data:
  # PostHog云服务配置
  POSTHOG_ENABLED: "true"
  POSTHOG_HOST: "https://app.posthog.com"  # US region
  # 或者使用EU region: https://eu.posthog.com
  
  # 其他配置与model-router-deployment.yaml相同...

---
# Model Router Secret (云服务)
apiVersion: v1
kind: Secret
metadata:
  name: model-router-secret-cloud
  namespace: voiceassistant-prod
type: Opaque
stringData:
  # PostHog项目API密钥
  # 获取方式:
  # 1. 访问 https://app.posthog.com
  # 2. 进入 Project Settings
  # 3. 复制 Project API Key (格式: phc_xxxxxxxxxxxx)
  POSTHOG_API_KEY: "phc_YOUR_PROJECT_API_KEY_FROM_POSTHOG_CLOUD"
  
  # 其他密钥...
  DB_PASSWORD: "your-db-password"
  OPENAI_API_KEY: "sk-..."

---
# 使用说明
# 1. 在PostHog云服务中创建项目并获取API Key
# 2. 更新上面的POSTHOG_API_KEY
# 3. 应用配置: kubectl apply -f posthog-cloud-config.yaml
# 4. 更新model-router deployment使用这个ConfigMap和Secret
