// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: knowledge/v1/knowledge.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DocumentStatus int32

const (
	DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED DocumentStatus = 0
	DocumentStatus_DOCUMENT_STATUS_UPLOADING   DocumentStatus = 1 // 上传中
	DocumentStatus_DOCUMENT_STATUS_PROCESSING  DocumentStatus = 2 // 处理中
	DocumentStatus_DOCUMENT_STATUS_READY       DocumentStatus = 3 // 就绪
	DocumentStatus_DOCUMENT_STATUS_FAILED      DocumentStatus = 4 // 失败
	DocumentStatus_DOCUMENT_STATUS_DELETED     DocumentStatus = 5 // 已删除
)

// Enum value maps for DocumentStatus.
var (
	DocumentStatus_name = map[int32]string{
		0: "DOCUMENT_STATUS_UNSPECIFIED",
		1: "DOCUMENT_STATUS_UPLOADING",
		2: "DOCUMENT_STATUS_PROCESSING",
		3: "DOCUMENT_STATUS_READY",
		4: "DOCUMENT_STATUS_FAILED",
		5: "DOCUMENT_STATUS_DELETED",
	}
	DocumentStatus_value = map[string]int32{
		"DOCUMENT_STATUS_UNSPECIFIED": 0,
		"DOCUMENT_STATUS_UPLOADING":   1,
		"DOCUMENT_STATUS_PROCESSING":  2,
		"DOCUMENT_STATUS_READY":       3,
		"DOCUMENT_STATUS_FAILED":      4,
		"DOCUMENT_STATUS_DELETED":     5,
	}
)

func (x DocumentStatus) Enum() *DocumentStatus {
	p := new(DocumentStatus)
	*p = x
	return p
}

func (x DocumentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledge_v1_knowledge_proto_enumTypes[0].Descriptor()
}

func (DocumentStatus) Type() protoreflect.EnumType {
	return &file_knowledge_v1_knowledge_proto_enumTypes[0]
}

func (x DocumentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentStatus.Descriptor instead.
func (DocumentStatus) EnumDescriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

type CollectionType int32

const (
	CollectionType_COLLECTION_TYPE_UNSPECIFIED CollectionType = 0
	CollectionType_COLLECTION_TYPE_PERSONAL    CollectionType = 1 // 个人
	CollectionType_COLLECTION_TYPE_SHARED      CollectionType = 2 // 共享
	CollectionType_COLLECTION_TYPE_PUBLIC      CollectionType = 3 // 公开
)

// Enum value maps for CollectionType.
var (
	CollectionType_name = map[int32]string{
		0: "COLLECTION_TYPE_UNSPECIFIED",
		1: "COLLECTION_TYPE_PERSONAL",
		2: "COLLECTION_TYPE_SHARED",
		3: "COLLECTION_TYPE_PUBLIC",
	}
	CollectionType_value = map[string]int32{
		"COLLECTION_TYPE_UNSPECIFIED": 0,
		"COLLECTION_TYPE_PERSONAL":    1,
		"COLLECTION_TYPE_SHARED":      2,
		"COLLECTION_TYPE_PUBLIC":      3,
	}
)

func (x CollectionType) Enum() *CollectionType {
	p := new(CollectionType)
	*p = x
	return p
}

func (x CollectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CollectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_knowledge_v1_knowledge_proto_enumTypes[1].Descriptor()
}

func (CollectionType) Type() protoreflect.EnumType {
	return &file_knowledge_v1_knowledge_proto_enumTypes[1]
}

func (x CollectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CollectionType.Descriptor instead.
func (CollectionType) EnumDescriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

type Document struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,4,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	ContentType   string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	StoragePath   string                 `protobuf:"bytes,8,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Status        DocumentStatus         `protobuf:"varint,9,opt,name=status,proto3,enum=knowledge.v1.DocumentStatus" json:"status,omitempty"`
	Metadata      *DocumentMetadata      `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       int32                  `protobuf:"varint,13,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Document) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Document) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *Document) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Document) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Document) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Document) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *Document) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED
}

func (x *Document) GetMetadata() *DocumentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Document) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DocumentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	PageCount     int32                  `protobuf:"varint,3,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	WordCount     int32                  `protobuf:"varint,4,opt,name=word_count,json=wordCount,proto3" json:"word_count,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Language      string                 `protobuf:"bytes,6,opt,name=language,proto3" json:"language,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentMetadata) Reset() {
	*x = DocumentMetadata{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentMetadata) ProtoMessage() {}

func (x *DocumentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentMetadata.ProtoReflect.Descriptor instead.
func (*DocumentMetadata) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentMetadata) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *DocumentMetadata) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *DocumentMetadata) GetWordCount() int32 {
	if x != nil {
		return x.WordCount
	}
	return 0
}

func (x *DocumentMetadata) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DocumentMetadata) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type UploadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Content       []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"` // 文件内容
	Metadata      *DocumentMetadata      `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDocumentRequest) Reset() {
	*x = UploadDocumentRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDocumentRequest) ProtoMessage() {}

func (x *UploadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDocumentRequest.ProtoReflect.Descriptor instead.
func (*UploadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *UploadDocumentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UploadDocumentRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UploadDocumentRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *UploadDocumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadDocumentRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadDocumentRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadDocumentRequest) GetMetadata() *DocumentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDocumentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CollectionId  string                 `protobuf:"bytes,3,opt,name=collection_id,json=collectionId,proto3" json:"collection_id,omitempty"`   // 可选过滤
	Status        DocumentStatus         `protobuf:"varint,4,opt,name=status,proto3,enum=knowledge.v1.DocumentStatus" json:"status,omitempty"` // 可选过滤
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *ListDocumentsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListDocumentsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListDocumentsRequest) GetCollectionId() string {
	if x != nil {
		return x.CollectionId
	}
	return ""
}

func (x *ListDocumentsRequest) GetStatus() DocumentStatus {
	if x != nil {
		return x.Status
	}
	return DocumentStatus_DOCUMENT_STATUS_UNSPECIFIED
}

func (x *ListDocumentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDocumentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *ListDocumentsResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ListDocumentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Metadata      *DocumentMetadata      `protobuf:"bytes,4,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDocumentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateDocumentRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateDocumentRequest) GetMetadata() *DocumentMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteDocumentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DownloadDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadDocumentRequest) Reset() {
	*x = DownloadDocumentRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadDocumentRequest) ProtoMessage() {}

func (x *DownloadDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadDocumentRequest.ProtoReflect.Descriptor instead.
func (*DownloadDocumentRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DownloadDocumentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DocumentChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ChunkIndex    int32                  `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentChunk) Reset() {
	*x = DocumentChunk{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentChunk) ProtoMessage() {}

func (x *DocumentChunk) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentChunk.ProtoReflect.Descriptor instead.
func (*DocumentChunk) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *DocumentChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DocumentChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *DocumentChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type Collection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Type          CollectionType         `protobuf:"varint,6,opt,name=type,proto3,enum=knowledge.v1.CollectionType" json:"type,omitempty"`
	Metadata      *CollectionMetadata    `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DocumentCount int32                  `protobuf:"varint,10,opt,name=document_count,json=documentCount,proto3" json:"document_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Collection) Reset() {
	*x = Collection{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Collection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Collection) ProtoMessage() {}

func (x *Collection) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Collection.ProtoReflect.Descriptor instead.
func (*Collection) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *Collection) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Collection) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Collection) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Collection) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Collection) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Collection) GetType() CollectionType {
	if x != nil {
		return x.Type
	}
	return CollectionType_COLLECTION_TYPE_UNSPECIFIED
}

func (x *Collection) GetMetadata() *CollectionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Collection) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Collection) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Collection) GetDocumentCount() int32 {
	if x != nil {
		return x.DocumentCount
	}
	return 0
}

type CollectionMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          map[string]string      `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AllowedUsers  []string               `protobuf:"bytes,2,rep,name=allowed_users,json=allowedUsers,proto3" json:"allowed_users,omitempty"` // 允许访问的用户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectionMetadata) Reset() {
	*x = CollectionMetadata{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectionMetadata) ProtoMessage() {}

func (x *CollectionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectionMetadata.ProtoReflect.Descriptor instead.
func (*CollectionMetadata) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *CollectionMetadata) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CollectionMetadata) GetAllowedUsers() []string {
	if x != nil {
		return x.AllowedUsers
	}
	return nil
}

type CreateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Type          CollectionType         `protobuf:"varint,5,opt,name=type,proto3,enum=knowledge.v1.CollectionType" json:"type,omitempty"`
	Metadata      *CollectionMetadata    `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCollectionRequest) Reset() {
	*x = CreateCollectionRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCollectionRequest) ProtoMessage() {}

func (x *CreateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCollectionRequest.ProtoReflect.Descriptor instead.
func (*CreateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{12}
}

func (x *CreateCollectionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCollectionRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateCollectionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCollectionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCollectionRequest) GetType() CollectionType {
	if x != nil {
		return x.Type
	}
	return CollectionType_COLLECTION_TYPE_UNSPECIFIED
}

func (x *CreateCollectionRequest) GetMetadata() *CollectionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCollectionRequest) Reset() {
	*x = GetCollectionRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCollectionRequest) ProtoMessage() {}

func (x *GetCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCollectionRequest.ProtoReflect.Descriptor instead.
func (*GetCollectionRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{13}
}

func (x *GetCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCollectionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Type          CollectionType         `protobuf:"varint,3,opt,name=type,proto3,enum=knowledge.v1.CollectionType" json:"type,omitempty"` // 可选过滤
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{14}
}

func (x *ListCollectionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListCollectionsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListCollectionsRequest) GetType() CollectionType {
	if x != nil {
		return x.Type
	}
	return CollectionType_COLLECTION_TYPE_UNSPECIFIED
}

func (x *ListCollectionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCollectionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collections   []*Collection          `protobuf:"bytes,1,rep,name=collections,proto3" json:"collections,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{15}
}

func (x *ListCollectionsResponse) GetCollections() []*Collection {
	if x != nil {
		return x.Collections
	}
	return nil
}

func (x *ListCollectionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Metadata      *CollectionMetadata    `protobuf:"bytes,5,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCollectionRequest) Reset() {
	*x = UpdateCollectionRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCollectionRequest) ProtoMessage() {}

func (x *UpdateCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCollectionRequest.ProtoReflect.Descriptor instead.
func (*UpdateCollectionRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCollectionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateCollectionRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCollectionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateCollectionRequest) GetMetadata() *CollectionMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCollectionRequest) Reset() {
	*x = DeleteCollectionRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCollectionRequest) ProtoMessage() {}

func (x *DeleteCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCollectionRequest.ProtoReflect.Descriptor instead.
func (*DeleteCollectionRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteCollectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteCollectionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DocumentVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Version       int32                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	StoragePath   string                 `protobuf:"bytes,4,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ChangeLog     string                 `protobuf:"bytes,8,opt,name=change_log,json=changeLog,proto3" json:"change_log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentVersion) Reset() {
	*x = DocumentVersion{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentVersion) ProtoMessage() {}

func (x *DocumentVersion) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentVersion.ProtoReflect.Descriptor instead.
func (*DocumentVersion) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{18}
}

func (x *DocumentVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentVersion) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentVersion) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DocumentVersion) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *DocumentVersion) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DocumentVersion) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *DocumentVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *DocumentVersion) GetChangeLog() string {
	if x != nil {
		return x.ChangeLog
	}
	return ""
}

type GetDocumentVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentVersionRequest) Reset() {
	*x = GetDocumentVersionRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentVersionRequest) ProtoMessage() {}

func (x *GetDocumentVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentVersionRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentVersionRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{19}
}

func (x *GetDocumentVersionRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetDocumentVersionRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetDocumentVersionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListDocumentVersionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentVersionsRequest) Reset() {
	*x = ListDocumentVersionsRequest{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentVersionsRequest) ProtoMessage() {}

func (x *ListDocumentVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentVersionsRequest) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{20}
}

func (x *ListDocumentVersionsRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ListDocumentVersionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListDocumentVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*DocumentVersion     `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentVersionsResponse) Reset() {
	*x = ListDocumentVersionsResponse{}
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentVersionsResponse) ProtoMessage() {}

func (x *ListDocumentVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_knowledge_v1_knowledge_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentVersionsResponse) Descriptor() ([]byte, []int) {
	return file_knowledge_v1_knowledge_proto_rawDescGZIP(), []int{21}
}

func (x *ListDocumentVersionsResponse) GetVersions() []*DocumentVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

var File_knowledge_v1_knowledge_proto protoreflect.FileDescriptor

const file_knowledge_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x1cknowledge/v1/knowledge.proto\x12\fknowledge.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x03\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12#\n" +
	"\rcollection_id\x18\x04 \x01(\tR\fcollectionId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x12!\n" +
	"\fstorage_path\x18\b \x01(\tR\vstoragePath\x124\n" +
	"\x06status\x18\t \x01(\x0e2\x1c.knowledge.v1.DocumentStatusR\x06status\x12:\n" +
	"\bmetadata\x18\n" +
	" \x01(\v2\x1e.knowledge.v1.DocumentMetadataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\r \x01(\x05R\aversion\"\x91\x02\n" +
	"\x10DocumentMetadata\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1d\n" +
	"\n" +
	"page_count\x18\x03 \x01(\x05R\tpageCount\x12\x1d\n" +
	"\n" +
	"word_count\x18\x04 \x01(\x05R\twordCount\x12<\n" +
	"\x04tags\x18\x05 \x03(\v2(.knowledge.v1.DocumentMetadata.TagsEntryR\x04tags\x12\x1a\n" +
	"\blanguage\x18\x06 \x01(\tR\blanguage\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xff\x01\n" +
	"\x15UploadDocumentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12#\n" +
	"\rcollection_id\x18\x03 \x01(\tR\fcollectionId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x12:\n" +
	"\bmetadata\x18\a \x01(\v2\x1e.knowledge.v1.DocumentMetadataR\bmetadata\"=\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xd8\x01\n" +
	"\x14ListDocumentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12#\n" +
	"\rcollection_id\x18\x03 \x01(\tR\fcollectionId\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.knowledge.v1.DocumentStatusR\x06status\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"c\n" +
	"\x15ListDocumentsResponse\x124\n" +
	"\tdocuments\x18\x01 \x03(\v2\x16.knowledge.v1.DocumentR\tdocuments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xb0\x01\n" +
	"\x15UpdateDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12?\n" +
	"\bmetadata\x18\x04 \x01(\v2\x1e.knowledge.v1.DocumentMetadataH\x01R\bmetadata\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_metadata\"@\n" +
	"\x15DeleteDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"B\n" +
	"\x17DownloadDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"_\n" +
	"\rDocumentChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\x05R\n" +
	"chunkIndex\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\"\x95\x03\n" +
	"\n" +
	"Collection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x120\n" +
	"\x04type\x18\x06 \x01(\x0e2\x1c.knowledge.v1.CollectionTypeR\x04type\x12<\n" +
	"\bmetadata\x18\a \x01(\v2 .knowledge.v1.CollectionMetadataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12%\n" +
	"\x0edocument_count\x18\n" +
	" \x01(\x05R\rdocumentCount\"\xb2\x01\n" +
	"\x12CollectionMetadata\x12>\n" +
	"\x04tags\x18\x01 \x03(\v2*.knowledge.v1.CollectionMetadata.TagsEntryR\x04tags\x12#\n" +
	"\rallowed_users\x18\x02 \x03(\tR\fallowedUsers\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x01\n" +
	"\x17CreateCollectionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x120\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1c.knowledge.v1.CollectionTypeR\x04type\x12<\n" +
	"\bmetadata\x18\x06 \x01(\v2 .knowledge.v1.CollectionMetadataR\bmetadata\"?\n" +
	"\x14GetCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xb1\x01\n" +
	"\x16ListCollectionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x120\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1c.knowledge.v1.CollectionTypeR\x04type\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"k\n" +
	"\x17ListCollectionsResponse\x12:\n" +
	"\vcollections\x18\x01 \x03(\v2\x18.knowledge.v1.CollectionR\vcollections\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xeb\x01\n" +
	"\x17UpdateCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x01R\vdescription\x88\x01\x01\x12A\n" +
	"\bmetadata\x18\x05 \x01(\v2 .knowledge.v1.CollectionMetadataH\x02R\bmetadata\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\v\n" +
	"\t_metadata\"B\n" +
	"\x17DeleteCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x97\x02\n" +
	"\x0fDocumentVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x05R\aversion\x12!\n" +
	"\fstorage_path\x18\x04 \x01(\tR\vstoragePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"change_log\x18\b \x01(\tR\tchangeLog\"o\n" +
	"\x19GetDocumentVersionRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"W\n" +
	"\x1bListDocumentVersionsRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"Y\n" +
	"\x1cListDocumentVersionsResponse\x129\n" +
	"\bversions\x18\x01 \x03(\v2\x1d.knowledge.v1.DocumentVersionR\bversions*\xc4\x01\n" +
	"\x0eDocumentStatus\x12\x1f\n" +
	"\x1bDOCUMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19DOCUMENT_STATUS_UPLOADING\x10\x01\x12\x1e\n" +
	"\x1aDOCUMENT_STATUS_PROCESSING\x10\x02\x12\x19\n" +
	"\x15DOCUMENT_STATUS_READY\x10\x03\x12\x1a\n" +
	"\x16DOCUMENT_STATUS_FAILED\x10\x04\x12\x1b\n" +
	"\x17DOCUMENT_STATUS_DELETED\x10\x05*\x87\x01\n" +
	"\x0eCollectionType\x12\x1f\n" +
	"\x1bCOLLECTION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18COLLECTION_TYPE_PERSONAL\x10\x01\x12\x1a\n" +
	"\x16COLLECTION_TYPE_SHARED\x10\x02\x12\x1a\n" +
	"\x16COLLECTION_TYPE_PUBLIC\x10\x032\xf5\b\n" +
	"\x10KnowledgeService\x12M\n" +
	"\x0eUploadDocument\x12#.knowledge.v1.UploadDocumentRequest\x1a\x16.knowledge.v1.Document\x12G\n" +
	"\vGetDocument\x12 .knowledge.v1.GetDocumentRequest\x1a\x16.knowledge.v1.Document\x12X\n" +
	"\rListDocuments\x12\".knowledge.v1.ListDocumentsRequest\x1a#.knowledge.v1.ListDocumentsResponse\x12M\n" +
	"\x0eUpdateDocument\x12#.knowledge.v1.UpdateDocumentRequest\x1a\x16.knowledge.v1.Document\x12M\n" +
	"\x0eDeleteDocument\x12#.knowledge.v1.DeleteDocumentRequest\x1a\x16.google.protobuf.Empty\x12X\n" +
	"\x10DownloadDocument\x12%.knowledge.v1.DownloadDocumentRequest\x1a\x1b.knowledge.v1.DocumentChunk0\x01\x12S\n" +
	"\x10CreateCollection\x12%.knowledge.v1.CreateCollectionRequest\x1a\x18.knowledge.v1.Collection\x12M\n" +
	"\rGetCollection\x12\".knowledge.v1.GetCollectionRequest\x1a\x18.knowledge.v1.Collection\x12^\n" +
	"\x0fListCollections\x12$.knowledge.v1.ListCollectionsRequest\x1a%.knowledge.v1.ListCollectionsResponse\x12S\n" +
	"\x10UpdateCollection\x12%.knowledge.v1.UpdateCollectionRequest\x1a\x18.knowledge.v1.Collection\x12Q\n" +
	"\x10DeleteCollection\x12%.knowledge.v1.DeleteCollectionRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\x12GetDocumentVersion\x12'.knowledge.v1.GetDocumentVersionRequest\x1a\x1d.knowledge.v1.DocumentVersion\x12m\n" +
	"\x14ListDocumentVersions\x12).knowledge.v1.ListDocumentVersionsRequest\x1a*.knowledge.v1.ListDocumentVersionsResponseB*Z(voiceassistant/api/proto/knowledge/v1;v1b\x06proto3"

var (
	file_knowledge_v1_knowledge_proto_rawDescOnce sync.Once
	file_knowledge_v1_knowledge_proto_rawDescData []byte
)

func file_knowledge_v1_knowledge_proto_rawDescGZIP() []byte {
	file_knowledge_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_knowledge_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_knowledge_v1_knowledge_proto_rawDesc), len(file_knowledge_v1_knowledge_proto_rawDesc)))
	})
	return file_knowledge_v1_knowledge_proto_rawDescData
}

var file_knowledge_v1_knowledge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_knowledge_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_knowledge_v1_knowledge_proto_goTypes = []any{
	(DocumentStatus)(0),                  // 0: knowledge.v1.DocumentStatus
	(CollectionType)(0),                  // 1: knowledge.v1.CollectionType
	(*Document)(nil),                     // 2: knowledge.v1.Document
	(*DocumentMetadata)(nil),             // 3: knowledge.v1.DocumentMetadata
	(*UploadDocumentRequest)(nil),        // 4: knowledge.v1.UploadDocumentRequest
	(*GetDocumentRequest)(nil),           // 5: knowledge.v1.GetDocumentRequest
	(*ListDocumentsRequest)(nil),         // 6: knowledge.v1.ListDocumentsRequest
	(*ListDocumentsResponse)(nil),        // 7: knowledge.v1.ListDocumentsResponse
	(*UpdateDocumentRequest)(nil),        // 8: knowledge.v1.UpdateDocumentRequest
	(*DeleteDocumentRequest)(nil),        // 9: knowledge.v1.DeleteDocumentRequest
	(*DownloadDocumentRequest)(nil),      // 10: knowledge.v1.DownloadDocumentRequest
	(*DocumentChunk)(nil),                // 11: knowledge.v1.DocumentChunk
	(*Collection)(nil),                   // 12: knowledge.v1.Collection
	(*CollectionMetadata)(nil),           // 13: knowledge.v1.CollectionMetadata
	(*CreateCollectionRequest)(nil),      // 14: knowledge.v1.CreateCollectionRequest
	(*GetCollectionRequest)(nil),         // 15: knowledge.v1.GetCollectionRequest
	(*ListCollectionsRequest)(nil),       // 16: knowledge.v1.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),      // 17: knowledge.v1.ListCollectionsResponse
	(*UpdateCollectionRequest)(nil),      // 18: knowledge.v1.UpdateCollectionRequest
	(*DeleteCollectionRequest)(nil),      // 19: knowledge.v1.DeleteCollectionRequest
	(*DocumentVersion)(nil),              // 20: knowledge.v1.DocumentVersion
	(*GetDocumentVersionRequest)(nil),    // 21: knowledge.v1.GetDocumentVersionRequest
	(*ListDocumentVersionsRequest)(nil),  // 22: knowledge.v1.ListDocumentVersionsRequest
	(*ListDocumentVersionsResponse)(nil), // 23: knowledge.v1.ListDocumentVersionsResponse
	nil,                                  // 24: knowledge.v1.DocumentMetadata.TagsEntry
	nil,                                  // 25: knowledge.v1.CollectionMetadata.TagsEntry
	(*timestamppb.Timestamp)(nil),        // 26: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 27: google.protobuf.Empty
}
var file_knowledge_v1_knowledge_proto_depIdxs = []int32{
	0,  // 0: knowledge.v1.Document.status:type_name -> knowledge.v1.DocumentStatus
	3,  // 1: knowledge.v1.Document.metadata:type_name -> knowledge.v1.DocumentMetadata
	26, // 2: knowledge.v1.Document.created_at:type_name -> google.protobuf.Timestamp
	26, // 3: knowledge.v1.Document.updated_at:type_name -> google.protobuf.Timestamp
	24, // 4: knowledge.v1.DocumentMetadata.tags:type_name -> knowledge.v1.DocumentMetadata.TagsEntry
	3,  // 5: knowledge.v1.UploadDocumentRequest.metadata:type_name -> knowledge.v1.DocumentMetadata
	0,  // 6: knowledge.v1.ListDocumentsRequest.status:type_name -> knowledge.v1.DocumentStatus
	2,  // 7: knowledge.v1.ListDocumentsResponse.documents:type_name -> knowledge.v1.Document
	3,  // 8: knowledge.v1.UpdateDocumentRequest.metadata:type_name -> knowledge.v1.DocumentMetadata
	1,  // 9: knowledge.v1.Collection.type:type_name -> knowledge.v1.CollectionType
	13, // 10: knowledge.v1.Collection.metadata:type_name -> knowledge.v1.CollectionMetadata
	26, // 11: knowledge.v1.Collection.created_at:type_name -> google.protobuf.Timestamp
	26, // 12: knowledge.v1.Collection.updated_at:type_name -> google.protobuf.Timestamp
	25, // 13: knowledge.v1.CollectionMetadata.tags:type_name -> knowledge.v1.CollectionMetadata.TagsEntry
	1,  // 14: knowledge.v1.CreateCollectionRequest.type:type_name -> knowledge.v1.CollectionType
	13, // 15: knowledge.v1.CreateCollectionRequest.metadata:type_name -> knowledge.v1.CollectionMetadata
	1,  // 16: knowledge.v1.ListCollectionsRequest.type:type_name -> knowledge.v1.CollectionType
	12, // 17: knowledge.v1.ListCollectionsResponse.collections:type_name -> knowledge.v1.Collection
	13, // 18: knowledge.v1.UpdateCollectionRequest.metadata:type_name -> knowledge.v1.CollectionMetadata
	26, // 19: knowledge.v1.DocumentVersion.created_at:type_name -> google.protobuf.Timestamp
	20, // 20: knowledge.v1.ListDocumentVersionsResponse.versions:type_name -> knowledge.v1.DocumentVersion
	4,  // 21: knowledge.v1.KnowledgeService.UploadDocument:input_type -> knowledge.v1.UploadDocumentRequest
	5,  // 22: knowledge.v1.KnowledgeService.GetDocument:input_type -> knowledge.v1.GetDocumentRequest
	6,  // 23: knowledge.v1.KnowledgeService.ListDocuments:input_type -> knowledge.v1.ListDocumentsRequest
	8,  // 24: knowledge.v1.KnowledgeService.UpdateDocument:input_type -> knowledge.v1.UpdateDocumentRequest
	9,  // 25: knowledge.v1.KnowledgeService.DeleteDocument:input_type -> knowledge.v1.DeleteDocumentRequest
	10, // 26: knowledge.v1.KnowledgeService.DownloadDocument:input_type -> knowledge.v1.DownloadDocumentRequest
	14, // 27: knowledge.v1.KnowledgeService.CreateCollection:input_type -> knowledge.v1.CreateCollectionRequest
	15, // 28: knowledge.v1.KnowledgeService.GetCollection:input_type -> knowledge.v1.GetCollectionRequest
	16, // 29: knowledge.v1.KnowledgeService.ListCollections:input_type -> knowledge.v1.ListCollectionsRequest
	18, // 30: knowledge.v1.KnowledgeService.UpdateCollection:input_type -> knowledge.v1.UpdateCollectionRequest
	19, // 31: knowledge.v1.KnowledgeService.DeleteCollection:input_type -> knowledge.v1.DeleteCollectionRequest
	21, // 32: knowledge.v1.KnowledgeService.GetDocumentVersion:input_type -> knowledge.v1.GetDocumentVersionRequest
	22, // 33: knowledge.v1.KnowledgeService.ListDocumentVersions:input_type -> knowledge.v1.ListDocumentVersionsRequest
	2,  // 34: knowledge.v1.KnowledgeService.UploadDocument:output_type -> knowledge.v1.Document
	2,  // 35: knowledge.v1.KnowledgeService.GetDocument:output_type -> knowledge.v1.Document
	7,  // 36: knowledge.v1.KnowledgeService.ListDocuments:output_type -> knowledge.v1.ListDocumentsResponse
	2,  // 37: knowledge.v1.KnowledgeService.UpdateDocument:output_type -> knowledge.v1.Document
	27, // 38: knowledge.v1.KnowledgeService.DeleteDocument:output_type -> google.protobuf.Empty
	11, // 39: knowledge.v1.KnowledgeService.DownloadDocument:output_type -> knowledge.v1.DocumentChunk
	12, // 40: knowledge.v1.KnowledgeService.CreateCollection:output_type -> knowledge.v1.Collection
	12, // 41: knowledge.v1.KnowledgeService.GetCollection:output_type -> knowledge.v1.Collection
	17, // 42: knowledge.v1.KnowledgeService.ListCollections:output_type -> knowledge.v1.ListCollectionsResponse
	12, // 43: knowledge.v1.KnowledgeService.UpdateCollection:output_type -> knowledge.v1.Collection
	27, // 44: knowledge.v1.KnowledgeService.DeleteCollection:output_type -> google.protobuf.Empty
	20, // 45: knowledge.v1.KnowledgeService.GetDocumentVersion:output_type -> knowledge.v1.DocumentVersion
	23, // 46: knowledge.v1.KnowledgeService.ListDocumentVersions:output_type -> knowledge.v1.ListDocumentVersionsResponse
	34, // [34:47] is the sub-list for method output_type
	21, // [21:34] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_knowledge_v1_knowledge_proto_init() }
func file_knowledge_v1_knowledge_proto_init() {
	if File_knowledge_v1_knowledge_proto != nil {
		return
	}
	file_knowledge_v1_knowledge_proto_msgTypes[6].OneofWrappers = []any{}
	file_knowledge_v1_knowledge_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_knowledge_v1_knowledge_proto_rawDesc), len(file_knowledge_v1_knowledge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knowledge_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_knowledge_v1_knowledge_proto_depIdxs,
		EnumInfos:         file_knowledge_v1_knowledge_proto_enumTypes,
		MessageInfos:      file_knowledge_v1_knowledge_proto_msgTypes,
	}.Build()
	File_knowledge_v1_knowledge_proto = out.File
	file_knowledge_v1_knowledge_proto_goTypes = nil
	file_knowledge_v1_knowledge_proto_depIdxs = nil
}
