---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indexing-service-config
  namespace: voiceassistant-prod
  labels:
    app: indexing-service
data:
  APP_NAME: "indexing-service"
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  PORT: "8004"
  WORKERS: "2"
  # Nacos
  NACOS_SERVER_ADDR: "nacos.voiceassistant-infra.svc.cluster.local:8848"
  # Redis
  REDIS_HOST: "redis.voiceassistant-infra.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "6"
  # Milvus
  MILVUS_HOST: "milvus.voiceassistant-infra.svc.cluster.local"
  MILVUS_PORT: "19530"
  # MinIO (文档存储)
  MINIO_ENDPOINT: "minio.voiceassistant-infra.svc.cluster.local:9000"
  MINIO_BUCKET: "documents"
  # Embedding配置
  EMBEDDING_MODEL: "bge-large-zh-v1.5"
  BATCH_SIZE: "32"

---
apiVersion: v1
kind: Secret
metadata:
  name: indexing-service-secret
  namespace: voiceassistant-prod
type: Opaque
stringData:
  REDIS_PASSWORD: ""
  MILVUS_USER: "root"
  MILVUS_PASSWORD: "Milvus"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexing-service
  namespace: voiceassistant-prod
  labels:
    app: indexing-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: indexing-service
      version: v1
  template:
    metadata:
      labels:
        app: indexing-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8004"
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: indexing-service-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: indexing-service
        image: ghcr.io/voiceassistant/indexing-service:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
          name: http
        envFrom:
        - configMapRef:
            name: indexing-service-config
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: indexing-service-secret
              key: REDIS_PASSWORD
        - name: MILVUS_USER
          valueFrom:
            secretKeyRef:
              name: indexing-service-secret
              key: MILVUS_USER
        - name: MILVUS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: indexing-service-secret
              key: MILVUS_PASSWORD
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: indexing-service-secret
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: indexing-service-secret
              key: MINIO_SECRET_KEY
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: indexing-service
  namespace: voiceassistant-prod
spec:
  type: ClusterIP
  selector:
    app: indexing-service
  ports:
  - port: 8004
    targetPort: 8004
    name: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: indexing-service-sa
  namespace: voiceassistant-prod

