# Nacos 配置中心连接配置（可选）
nacos:
  server_addr: "localhost"
  server_port: 8848
  namespace: ""
  group: "VoiceHelper"
  data_id: "ai-orchestrator.yaml"
  username: ""
  password: ""
  log_dir: "/tmp/nacos/log"
  cache_dir: "/tmp/nacos/cache"
  log_level: "info"
  timeout_ms: 5000

server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 60s

service:
  name: ai-orchestrator
  version: v2.0.0

engines:
  agent:
    endpoint: agent-engine:9000
    timeout: 60s
  rag:
    endpoint: rag-engine:9000
    timeout: 30s
  voice:
    endpoint: voice-engine:9000
    timeout: 30s
  multimodal:
    endpoint: multimodal-engine:9000
    timeout: 45s

model_router:
  endpoint: model-router:9000
  timeout: 30s

observability:
  tracing:
    enabled: true
    endpoint: otel-collector:4317
  metrics:
    enabled: true
  logging:
    level: info
    format: json

# 意图识别配置
intent_recognition:
  enabled: true
  use_cache: true
  cache_size: 10000
  cache_ttl: 600  # 秒
  min_confidence: 0.7
  use_fallback: true
  recognizers:
    - type: rule
      enabled: true
      priority: 1
    - type: llm
      enabled: true
      priority: 2
      timeout: 5s
      model: "gpt-3.5-turbo"
