# 算法服务配置文件
# 用于客户端连接各个算法服务

services:
  http:
    # Agent Engine - 智能代理引擎
    agent-engine:
      url: "http://localhost:8010"
      timeout: 60s
      description: "Agent执行、工具调用、记忆管理、Multi-Agent、Self-RAG"

    # RAG Engine - 已合并到 Knowledge Service
    # rag-engine:
    #   url: "http://localhost:8006"
    #   timeout: 30s
    #   description: "RAG问答、查询改写、上下文构建（已合并到knowledge-service）"

    # Retrieval Service - 检索服务
    retrieval-service:
      url: "http://localhost:8012"
      timeout: 30s
      description: "向量检索、混合检索、重排序"

    # Voice Engine - 语音处理引擎
    voice-engine:
      url: "http://localhost:8004"
      timeout: 30s
      description: "ASR、TTS、VAD、语音流处理"

    # Multimodal Engine - 多模态引擎
    multimodal-engine:
      url: "http://localhost:8008"
      timeout: 30s
      description: "OCR、视觉理解、图像分析"

    # Model Adapter - 模型适配器
    model-adapter:
      url: "http://localhost:8005"
      timeout: 60s
      description: "LLM适配、协议转换、成本计算"

    # Indexing Service - 文档索引服务
    indexing-service:
      url: "http://localhost:8011"
      timeout: 300s
      description: "文档索引、向量化、知识图谱构建"

    # Vector Store Adapter - 向量库适配器
    vector-store-adapter:
      url: "http://localhost:8009"
      timeout: 30s
      description: "向量库适配（Milvus/pgvector）"

    # Knowledge Service - 知识服务（合并后的统一版本）
    knowledge-service:
      url: "http://localhost:8006"
      timeout: 30s
      description: "知识图谱管理 + 文档管理 + GraphRAG"
# Docker Compose 环境配置
# 当服务运行在Docker Compose中时，使用服务名作为主机名
# docker-compose:
#   services:
#     http:
#       agent-engine:
#         url: "http://agent-engine:8010"
#       rag-engine:
#         url: "http://rag-engine:8006"
#       retrieval-service:
#         url: "http://retrieval-service:8012"
#       voice-engine:
#         url: "http://voice-engine:8004"
#       multimodal-engine:
#         url: "http://multimodal-engine:8008"
#       model-adapter:
#         url: "http://model-adapter:8005"
#       indexing-service:
#         url: "http://indexing-service:8000"
#       vector-store-adapter:
#         url: "http://vector-store-adapter:8009"

# Kubernetes 环境配置
# kubernetes:
#   services:
#     http:
#       agent-engine:
#         url: "http://agent-engine.voicehelper.svc.cluster.local:8010"
#       rag-engine:
#         url: "http://rag-engine.voicehelper.svc.cluster.local:8006"
#       retrieval-service:
#         url: "http://retrieval-service.voicehelper.svc.cluster.local:8012"
#       voice-engine:
#         url: "http://voice-engine.voicehelper.svc.cluster.local:8004"
#       multimodal-engine:
#         url: "http://multimodal-engine.voicehelper.svc.cluster.local:8008"
#       model-adapter:
#         url: "http://model-adapter.voicehelper.svc.cluster.local:8005"
#       indexing-service:
#         url: "http://indexing-service.voicehelper.svc.cluster.local:8000"
#       vector-store-adapter:
#         url: "http://vector-store-adapter.voicehelper.svc.cluster.local:8009"
