# Identity Service 配置文件

# Nacos 配置中心连接配置（可选）
nacos:
  server_addr: "localhost"
  server_port: 8848
  namespace: ""
  group: "VoiceAssistant"
  data_id: "identity-service.yaml"
  username: ""
  password: ""
  log_dir: "/tmp/nacos/log"
  cache_dir: "/tmp/nacos/cache"
  log_level: "info"
  timeout_ms: 5000

server:
  http:
    addr: 0.0.0.0:8000
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s

data:
  database:
    driver: postgres
    source: postgresql://voiceassistant:password@postgres:5432/voiceassistant?sslmode=disable&search_path=identity
  redis:
    addr: redis:6379
    password: ""
    db: 0
    read_timeout: 1s
    write_timeout: 1s
    dial_timeout: 1s
    pool_size: 10

auth:
  jwt:
    secret: ${VAULT:secret/jwt#secret} # 从 Vault 读取
    issuer: voiceassistant.ai
    access_token_ttl: 1h # 1小时
    refresh_token_ttl: 168h # 7天
  password:
    bcrypt_cost: 12 # bcrypt 强度

  # OAuth2/SSO 配置
  oauth2:
    google:
      enabled: true
      client_id: ${VAULT:secret/oauth/google#client_id}
      client_secret: ${VAULT:secret/oauth/google#client_secret}
      redirect_url: "https://api.voiceassistant.ai/auth/google/callback"
    github:
      enabled: true
      client_id: ${VAULT:secret/oauth/github#client_id}
      client_secret: ${VAULT:secret/oauth/github#client_secret}
      redirect_url: "https://api.voiceassistant.ai/auth/github/callback"
    wechat:
      enabled: false
      app_id: ${VAULT:secret/oauth/wechat#app_id}
      app_secret: ${VAULT:secret/oauth/wechat#app_secret}
      redirect_url: "https://api.voiceassistant.ai/auth/wechat/callback"

service:
  name: identity-service
  version: v2.0.0
  metadata:
    environment: production
    region: us-west-2

# 可观测性配置
observability:
  tracing:
    enabled: true
    endpoint: otel-collector:4317
    sampler: always_on
  metrics:
    enabled: true
    endpoint: prometheus:9090
  logging:
    level: info
    format: json
    output: stdout

# 限流配置
ratelimit:
  enabled: true
  requests_per_minute: 100
  burst: 50

# Vault 配置
vault:
  addr: http://vault:8200
  token: ${VAULT_TOKEN}
  role: identity-service
