# Nacos 配置中心连接配置（可选）
nacos:
  server_addr: "localhost"
  server_port: 8848
  namespace: ""
  group: "VoiceAssistant"
  data_id: "knowledge-service.yaml"
  username: ""
  password: ""
  log_dir: "/tmp/nacos/log"
  cache_dir: "/tmp/nacos/cache"
  log_level: "info"
  timeout_ms: 5000

server:
  http:
    addr: 0.0.0.0:8000
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s

data:
  database:
    driver: postgres
    source: postgresql://voiceassistant:password@postgres:5432/voiceassistant?sslmode=disable&search_path=knowledge
  redis:
    addr: redis:6379
    db: 2
  minio:
    endpoint: minio:9000
    access_key: minioadmin
    secret_key: minioadmin
    bucket: voiceassistant-documents
    use_ssl: false

kafka:
  brokers:
    - kafka:9092
  topics:
    document_events: document.events

service:
  name: knowledge-service
  version: v2.0.0

observability:
  tracing:
    enabled: true
    endpoint: otel-collector:4317
  metrics:
    enabled: true
  logging:
    level: info
    format: json
