# Model Router 服务配置

server:
  http:
    addr: ":9004"
    timeout: 30s
    read_timeout: 30s
    write_timeout: 30s
  grpc:
    addr: ":9005"
    timeout: 30s

data:
  database:
    driver: postgres
    source: "host=localhost port=5432 user=postgres password=postgres dbname=model_router sslmode=disable"
    max_idle_conns: 10
    max_open_conns: 100
    conn_max_lifetime: 3600s
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s

models:
  # 模型配置文件路径
  config_path: "configs/models.yaml"
  # 健康检查周期
  health_check_period: 30s
  # 是否启用 A/B 测试
  enable_ab_test: true

observability:
  tracing:
    enabled: true
    endpoint: "http://localhost:14268/api/traces"
    sampler: 0.1 # 10% 采样率
  metrics:
    enabled: true
    port: 9090
    path: "/metrics"
  logging:
    level: "info" # debug, info, warn, error
    format: "json" # json, text
