# Model Router Service Configuration

server:
  http:
    addr: 0.0.0.0:9004
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9005
    timeout: 30s

# 数据库配置
database:
  driver: postgres
  host: localhost
  port: 5432
  database: voiceassistant
  username: postgres
  password: postgres
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600s
  log_level: info

# Redis配置
redis:
  addr: localhost:6379
  password: ""
  db: 0
  pool_size: 100
  min_idle_conns: 10
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

# A/B测试配置
abtest:
  enabled: true
  cache_ttl: 1h
  user_variant_cache_ttl: 24h
  default_strategy: consistent_hash

  # PostHog集成（可选）
  posthog:
    enabled: false
    api_key: ""
    host: https://app.posthog.com

# 模型注册表
models:
  # OpenAI Models
  - id: gpt-4-turbo-preview
    name: GPT-4 Turbo
    provider: openai
    model_name: gpt-4-turbo-preview
    capabilities:
      - chat
      - streaming
      - function_calling
    context_length: 128000
    cost:
      input_per_1k: 0.01
      output_per_1k: 0.03
    priority: 100
    enabled: true

  - id: gpt-3.5-turbo
    name: GPT-3.5 Turbo
    provider: openai
    model_name: gpt-3.5-turbo
    capabilities:
      - chat
      - streaming
      - function_calling
    context_length: 16385
    cost:
      input_per_1k: 0.0005
      output_per_1k: 0.0015
    priority: 80
    enabled: true

  # Claude Models
  - id: claude-3-opus-20240229
    name: Claude-3 Opus
    provider: anthropic
    model_name: claude-3-opus-20240229
    capabilities:
      - chat
      - streaming
    context_length: 200000
    cost:
      input_per_1k: 0.015
      output_per_1k: 0.075
    priority: 95
    enabled: true

  - id: claude-3-sonnet-20240229
    name: Claude-3 Sonnet
    provider: anthropic
    model_name: claude-3-sonnet-20240229
    capabilities:
      - chat
      - streaming
    context_length: 200000
    cost:
      input_per_1k: 0.003
      output_per_1k: 0.015
    priority: 85
    enabled: true

  # Zhipu AI
  - id: glm-4
    name: GLM-4
    provider: zhipu
    model_name: glm-4
    capabilities:
      - chat
      - streaming
    context_length: 128000
    cost:
      input_per_1k: 0.0001
      output_per_1k: 0.0001
    priority: 75
    enabled: true

  # Qwen
  - id: qwen-turbo
    name: Qwen Turbo
    provider: qwen
    model_name: qwen-turbo
    capabilities:
      - chat
      - streaming
    context_length: 8192
    cost:
      input_per_1k: 0.0002
      output_per_1k: 0.0002
    priority: 70
    enabled: true

# 路由策略配置
routing:
  default_strategy: cheapest
  strategies:
    - cheapest
    - fastest
    - most_available
    - best_quality
    - round_robin
    - random

# 成本优化配置
cost_optimizer:
  enabled: true
  budget_alert_threshold: 100.0 # USD
  daily_budget_limit: 500.0 # USD
  monthly_budget_limit: 15000.0 # USD

# 熔断器配置
circuit_breaker:
  enabled: true
  failure_threshold: 5
  success_threshold: 2
  timeout: 60s
  half_open_max_requests: 3

# 健康检查配置
health_check:
  enabled: true
  interval: 30s
  timeout: 5s
  unhealthy_threshold: 3
  healthy_threshold: 2

# 可观测性配置
observability:
  metrics:
    enabled: true
    path: /metrics
  tracing:
    enabled: true
    endpoint: http://localhost:14268/api/traces
    sampler:
      type: probabilistic
      param: 0.1
  logging:
    level: info
    format: json
    output: stdout

# 限流配置
rate_limit:
  enabled: true
  requests_per_second: 100
  burst: 200
  by_user: true
  by_tenant: true
