# 模型配置文件

models:
  # OpenAI Models
  - id: "gpt-4-turbo"
    name: "gpt-4-turbo-preview"
    display_name: "GPT-4 Turbo"
    provider: "openai"
    type: "chat"
    status: "active"
    endpoint: "https://api.openai.com/v1/chat/completions"
    api_key_env: "OPENAI_API_KEY" # 从环境变量读取
    max_tokens: 4096
    context_window: 128000
    input_price_per_k: 0.01
    output_price_per_k: 0.03
    priority: 90
    weight: 100
    timeout: 60
    retry_count: 3
    rate_limit: 500
    capabilities:
      - "chat"
      - "streaming"
      - "function_calling"
      - "vision"

  - id: "gpt-3.5-turbo"
    name: "gpt-3.5-turbo"
    display_name: "GPT-3.5 Turbo"
    provider: "openai"
    type: "chat"
    status: "active"
    endpoint: "https://api.openai.com/v1/chat/completions"
    api_key_env: "OPENAI_API_KEY"
    max_tokens: 4096
    context_window: 16385
    input_price_per_k: 0.0005
    output_price_per_k: 0.0015
    priority: 70
    weight: 150
    timeout: 30
    retry_count: 3
    rate_limit: 3000
    capabilities:
      - "chat"
      - "streaming"
      - "function_calling"

  # Anthropic Models
  - id: "claude-3-opus"
    name: "claude-3-opus-20240229"
    display_name: "Claude 3 Opus"
    provider: "anthropic"
    type: "chat"
    status: "active"
    endpoint: "https://api.anthropic.com/v1/messages"
    api_key_env: "ANTHROPIC_API_KEY"
    max_tokens: 4096
    context_window: 200000
    input_price_per_k: 0.015
    output_price_per_k: 0.075
    priority: 95
    weight: 80
    timeout: 60
    retry_count: 3
    rate_limit: 400
    capabilities:
      - "chat"
      - "streaming"
      - "vision"
      - "long_context"

  - id: "claude-3-sonnet"
    name: "claude-3-sonnet-20240229"
    display_name: "Claude 3 Sonnet"
    provider: "anthropic"
    type: "chat"
    status: "active"
    endpoint: "https://api.anthropic.com/v1/messages"
    api_key_env: "ANTHROPIC_API_KEY"
    max_tokens: 4096
    context_window: 200000
    input_price_per_k: 0.003
    output_price_per_k: 0.015
    priority: 85
    weight: 120
    timeout: 45
    retry_count: 3
    rate_limit: 800
    capabilities:
      - "chat"
      - "streaming"
      - "vision"
      - "long_context"

  - id: "claude-3-haiku"
    name: "claude-3-haiku-20240307"
    display_name: "Claude 3 Haiku"
    provider: "anthropic"
    type: "chat"
    status: "active"
    endpoint: "https://api.anthropic.com/v1/messages"
    api_key_env: "ANTHROPIC_API_KEY"
    max_tokens: 4096
    context_window: 200000
    input_price_per_k: 0.00025
    output_price_per_k: 0.00125
    priority: 75
    weight: 180
    timeout: 30
    retry_count: 3
    rate_limit: 1500
    capabilities:
      - "chat"
      - "streaming"
      - "long_context"

  # Google Models
  - id: "gemini-pro"
    name: "gemini-pro"
    display_name: "Gemini Pro"
    provider: "google"
    type: "chat"
    status: "active"
    endpoint: "https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent"
    api_key_env: "GOOGLE_API_KEY"
    max_tokens: 2048
    context_window: 32768
    input_price_per_k: 0.0005
    output_price_per_k: 0.0015
    priority: 80
    weight: 140
    timeout: 30
    retry_count: 3
    rate_limit: 2000
    capabilities:
      - "chat"
      - "streaming"

  # 本地模型示例
  - id: "local-llama-3"
    name: "llama-3-70b"
    display_name: "Llama 3 70B (Local)"
    provider: "local"
    type: "chat"
    status: "inactive" # 默认不启用
    endpoint: "http://localhost:8000/v1/chat/completions"
    max_tokens: 8192
    context_window: 8192
    input_price_per_k: 0.0 # 本地模型无成本
    output_price_per_k: 0.0
    priority: 60
    weight: 100
    timeout: 120
    retry_count: 2
    rate_limit: 100
    capabilities:
      - "chat"
      - "streaming"
