# RAG Enhanced Configuration
# 阶段一/二增强配置示例

# ===== Vector Store =====
vector_store:
  adapter_url: "http://vector-store-adapter:8003"
  collection_name: "document_chunks"
  backend: "milvus"  # milvus | pgvector
  timeout: 30.0

# ===== Neo4j Graph Database =====
neo4j:
  uri: "bolt://neo4j:7687"
  user: "neo4j"
  password: "${NEO4J_PASSWORD}"
  database: "neo4j"
  max_connection_lifetime: 3600
  max_connection_pool_size: 50
  connection_timeout: 30

# ===== Entity & Relation Extraction =====
entity_extraction:
  # spacy | transformer
  method: "transformer"

  # spaCy model
  spacy_model: "en_core_web_sm"

  # Transformer model for NER
  transformer_model: "dslim/bert-base-NER"

  # Extract with context window
  context_window: 50

relation_extraction:
  # rule_based | llm
  method: "rule_based"

  # LLM config (if method=llm)
  llm_endpoint: "http://model-adapter:8010"
  llm_model: "qwen-7b"

  # Relation types
  relation_types:
    - "is_a"
    - "part_of"
    - "located_in"
    - "works_for"
    - "created_by"
    - "owns"
    - "related_to"
    - "caused_by"
    - "results_in"

  # Filtering
  min_confidence: 0.5

# ===== Incremental Indexing =====
incremental_indexing:
  # Redis for version management
  redis_url: "redis://redis:6379/0"
  version_ttl_days: 365

  # Auto delete old data on reindex
  auto_delete_old: true

  # Retry policy
  max_retries: 3
  retry_delay_seconds: 5

# ===== BM25 Retrieval =====
bm25:
  # Load corpus on startup
  load_on_startup: true

  # Corpus size warning threshold
  large_corpus_threshold: 10000

  # Elasticsearch (production alternative)
  use_elasticsearch: false
  elasticsearch_url: "http://elasticsearch:9200"
  elasticsearch_index: "documents"

# ===== Reranking =====
reranking:
  # cross_encoder | llm
  method: "cross_encoder"

  # Cross-Encoder model
  cross_encoder_model: "BAAI/bge-reranker-base"

  # LLM reranking (if method=llm)
  llm:
    endpoint: "http://model-adapter:8010"
    model: "qwen-7b"
    temperature: 0.1
    max_tokens: 10
    concurrency_limit: 5

# ===== Compression =====
compression:
  # keyword | semantic | llm
  method: "semantic"

  # Semantic compression
  semantic:
    embedding_model: "paraphrase-multilingual-MiniLM-L12-v2"
    min_relevance_score: 0.3
    max_sentences: 5

  # Keyword compression
  keyword:
    min_relevance_score: 0.3
    max_sentences: 10

  # Target compression ratio
  target_compression_ratio: 0.5  # 50% compression

# ===== Conversation Context =====
conversation:
  service_url: "http://conversation-service:8002"

  # History for query rewrite
  max_history_messages: 5

  # Timeout
  fetch_timeout: 5.0

  # Fallback on error
  fallback_to_no_history: true

# ===== RAG Pipeline =====
rag_pipeline:
  # Retrieval mode: vector | bm25 | hybrid | graph
  default_mode: "hybrid"

  # Hybrid weights
  hybrid_weights:
    vector: 0.4
    bm25: 0.3
    graph: 0.3

  # Top K
  retrieval_top_k: 20
  rerank_top_k: 10
  final_top_k: 5

  # Enable features
  enable_query_rewrite: true
  enable_compression: true
  enable_reranking: true

  # LLM for generation
  llm:
    endpoint: "http://model-adapter:8010"
    model: "qwen-14b-chat"
    temperature: 0.7
    max_tokens: 2000
    stream: true

# ===== Observability =====
observability:
  # Metrics
  enable_metrics: true
  metrics_port: 9090

  # Logging
  log_level: "INFO"
  structured_logging: true

  # Tracing
  enable_tracing: true
  otel_endpoint: "http://jaeger:4317"

  # Track latencies
  track_component_latencies: true

# ===== Performance =====
performance:
  # Entity extraction
  entity_extraction_batch_size: 10
  entity_extraction_workers: 4

  # LLM reranking
  rerank_batch_size: 5
  rerank_timeout: 30.0

  # Compression
  compression_timeout: 5.0

  # Cache
  enable_result_cache: true
  cache_ttl_seconds: 3600

# ===== NFR Targets =====
nfr:
  # Latency (ms)
  retrieval_p95: 500
  rerank_p95: 2000
  compression_p95: 200
  e2e_rag_p95: 2500

  # Availability
  target_availability: 0.999

  # Quality
  retrieval_recall_at_5: 0.85
  rerank_ndcg_at_5: 0.90
  compression_info_retention: 0.90
