version: '3.8'

services:
  identity-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: voiceassistant/identity-service:latest
    container_name: identity-service
    ports:
      - "9000:9000"  # gRPC port
      - "8000:8000"  # HTTP port
    environment:
      - ENV=development
      - LOG_LEVEL=info
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=voiceassistant
      - POSTGRES_PASSWORD=voiceassistant123
      - POSTGRES_DB=voiceassistant
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=dev-token
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - postgres
      - redis
      - vault
    networks:
      - voiceassistant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  postgres:
    image: postgres:15-alpine
    container_name: identity-postgres
    environment:
      - POSTGRES_USER=voiceassistant
      - POSTGRES_PASSWORD=voiceassistant123
      - POSTGRES_DB=voiceassistant
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../../migrations/postgres:/docker-entrypoint-initdb.d
    networks:
      - voiceassistant-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: identity-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - voiceassistant-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  vault:
    image: hashicorp/vault:latest
    container_name: identity-vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    networks:
      - voiceassistant-network
    restart: unless-stopped

volumes:
  postgres-data:
  redis-data:

networks:
  voiceassistant-network:
    driver: bridge
