---
apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-service-config
  namespace: voiceassistant-prod
  labels:
    app: identity-service
data:
  APP_NAME: "identity-service"
  APP_ENV: "production"
  LOG_LEVEL: "info"
  HTTP_PORT: "8080"
  GRPC_PORT: "9000"
  METRICS_PORT: "9090"
  DB_HOST: "postgres.voiceassistant-infra.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "identity"
  DB_SSL_MODE: "disable"
  REDIS_ADDR: "redis.voiceassistant-infra.svc.cluster.local:6379"
  NACOS_ADDR: "nacos.voiceassistant-infra.svc.cluster.local:8848"
  JWT_ISSUER: "https://identity.voiceassistant.com"
  JWT_AUDIENCE: "voiceassistant-api"

---
apiVersion: v1
kind: Secret
metadata:
  name: identity-service-secret
  namespace: voiceassistant-prod
  labels:
    app: identity-service
type: Opaque
stringData:
  DB_PASSWORD: "changeme"
  REDIS_PASSWORD: ""
  JWT_SECRET: "your-jwt-secret-key-change-in-production"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: voiceassistant-prod
  labels:
    app: identity-service
    version: v1
    component: auth
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: identity-service
      version: v1
  template:
    metadata:
      labels:
        app: identity-service
        version: v1
        component: auth
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: identity-service-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z $DB_HOST $DB_PORT; do echo waiting for postgres; sleep 2; done']
        envFrom:
        - configMapRef:
            name: identity-service-config
      containers:
      - name: identity-service
        image: ghcr.io/voiceassistant/identity-service:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 9000
          name: grpc
          protocol: TCP
        - containerPort: 9090
          name: metrics
          protocol: TCP
        envFrom:
        - configMapRef:
            name: identity-service-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: identity-service-secret
              key: DB_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: identity-service-secret
              key: REDIS_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: identity-service-secret
              key: JWT_SECRET
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: voiceassistant-prod
  labels:
    app: identity-service
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: grpc
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-service-sa
  namespace: voiceassistant-prod
  labels:
    app: identity-service

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: identity-service-hpa
  namespace: voiceassistant-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: identity-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: identity-service-pdb
  namespace: voiceassistant-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: identity-service

