---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: voiceassistant-prod
  labels:
    app: notification-service
data:
  APP_NAME: "notification-service"
  APP_ENV: "production"
  LOG_LEVEL: "info"
  HTTP_PORT: "9006"
  GRPC_PORT: "9106"
  METRICS_PORT: "9090"
  DB_HOST: "postgres.voiceassistant-infra.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "notification"
  REDIS_ADDR: "redis.voiceassistant-infra.svc.cluster.local:6379"
  KAFKA_BROKERS: "kafka.voiceassistant-infra.svc.cluster.local:9092"
  NACOS_ADDR: "nacos.voiceassistant-infra.svc.cluster.local:8848"

---
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
  namespace: voiceassistant-prod
type: Opaque
stringData:
  DB_PASSWORD: "changeme"
  REDIS_PASSWORD: ""
  SMTP_PASSWORD: ""
  WEBHOOK_SECRET: ""

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: voiceassistant-prod
  labels:
    app: notification-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
      version: v1
  template:
    metadata:
      labels:
        app: notification-service
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: notification-service-sa
      containers:
      - name: notification-service
        image: ghcr.io/voiceassistant/notification-service:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9006
          name: http
        - containerPort: 9106
          name: grpc
        - containerPort: 9090
          name: metrics
        envFrom:
        - configMapRef:
            name: notification-service-config
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: notification-service-secret
              key: DB_PASSWORD
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: voiceassistant-prod
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
  - port: 9006
    targetPort: 9006
    name: http

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  namespace: voiceassistant-prod

