version: "3.8"

services:
  indexing-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: voiceassistant/indexing-service:latest
    container_name: indexing-service
    ports:
      - "8011:8011"
    environment:
      - ENV=development
      - LOG_LEVEL=info
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MILVUS_HOST=milvus
      - MILVUS_PORT=19530
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=voiceassistant
      - POSTGRES_PASSWORD=voiceassistant123
      - POSTGRES_DB=voiceassistant
      - KAFKA_BROKERS=kafka:9092
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - minio
      - milvus
      - postgres
      - kafka
    networks:
      - voiceassistant-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import requests; requests.get('http://localhost:8011/health')",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs

  milvus:
    image: milvusdb/milvus:latest
    container_name: indexing-milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    depends_on:
      - etcd
      - minio
    networks:
      - voiceassistant-network
    restart: unless-stopped
    volumes:
      - milvus-data:/var/lib/milvus

  etcd:
    image: quay.io/coreos/etcd:latest
    container_name: indexing-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
    ports:
      - "2379:2379"
      - "2380:2380"
    networks:
      - voiceassistant-network
    restart: unless-stopped
    volumes:
      - etcd-data:/etcd

  minio:
    image: minio/minio:latest
    container_name: indexing-minio
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio-data:/data
    networks:
      - voiceassistant-network
    restart: unless-stopped
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:15-alpine
    container_name: indexing-postgres
    environment:
      - POSTGRES_USER=voiceassistant
      - POSTGRES_PASSWORD=voiceassistant123
      - POSTGRES_DB=voiceassistant
    ports:
      - "5438:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - voiceassistant-network
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    container_name: indexing-kafka
    ports:
      - "9096:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - voiceassistant-network
    restart: unless-stopped

volumes:
  milvus-data:
  etcd-data:
  minio-data:
  postgres-data:
  kafka-data:

networks:
  voiceassistant-network:
    driver: bridge
