version: '3.8'

services:
  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: voicehelper/analytics-service:latest
    container_name: analytics-service
    ports:
      - "9006:9006"  # gRPC port
      - "8006:8006"  # HTTP port
    environment:
      - ENV=development
      - LOG_LEVEL=info
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DB=voicehelper
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - clickhouse
      - redis
    networks:
      - voicehelper-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: analytics-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    environment:
      - CLICKHOUSE_DB=voicehelper
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - ../../migrations/clickhouse:/docker-entrypoint-initdb.d
    networks:
      - voicehelper-network
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  redis:
    image: redis:7-alpine
    container_name: analytics-redis
    ports:
      - "6385:6379"
    volumes:
      - redis-data:/data
    networks:
      - voicehelper-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  clickhouse-data:
  redis-data:

networks:
  voicehelper-network:
    driver: bridge
