[tool.ruff]
# 目标Python版本
target-version = "py311"

# 每行最大字符数
line-length = 100

# 排除的目录
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
    "*.egg-info",
]

[tool.ruff.lint]
# 启用的规则集
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG", # flake8-unused-arguments
    "SIM", # flake8-simplify
]

# 忽略的规则
ignore = [
    "E501",  # line-too-long (由formatter处理)
    "B008",  # do not perform function calls in argument defaults
    "W191",  # indentation contains tabs
]

# 允许自动修复
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
# 测试文件允许使用assert
"tests/**/*.py" = ["S101"]
"test_*.py" = ["S101"]

[tool.ruff.format]
# 使用双引号
quote-style = "double"

# 使用空格缩进
indent-style = "space"

# 尊重magic trailing comma
skip-magic-trailing-comma = false

[tool.mypy]
# 基础配置
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false  # 逐步启用
disallow_any_generics = false
disallow_subclassing_any = false
disallow_untyped_calls = false
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

# 第三方库忽略
[[tool.mypy.overrides]]
module = [
    "fastapi.*",
    "pydantic.*",
    "redis.*",
    "pymilvus.*",
    "opentelemetry.*",
    "prometheus_client.*",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
# pytest配置
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--verbose",
    "--strict-markers",
    "--cov=.",
    "--cov-report=term-missing",
    "--cov-report=html",
]

[tool.coverage.run]
# 覆盖率配置
source = ["."]
omit = [
    "*/tests/*",
    "*/test_*.py",
    "*/__pycache__/*",
    "*/venv/*",
    "*/.venv/*",
]

[tool.coverage.report]
# 覆盖率报告
precision = 2
show_missing = true
skip_covered = false

[tool.black]
# Black代码格式化器
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # 默认排除
  \.git
  | \.venv
  | venv
  | \.mypy_cache
  | \.pytest_cache
  | build
  | dist
)/
'''
